--
-- BDS_MATERIAL_PLANT_LOCAL  (Table) 
--
CREATE TABLE BDS.BDS_MATERIAL_PLANT_LOCAL
(
  SAP_MATERIAL_CODE               VARCHAR2(18 CHAR) NOT NULL,
  PLANT_CODE                      VARCHAR2(4 CHAR) NOT NULL,
  BDS_MATERIAL_DESC_EN            VARCHAR2(40 CHAR)     NULL,
  BDS_MATERIAL_DESC_TH            VARCHAR2(40 CHAR)     NULL,
  BDS_MATERIAL_DESC_ZH            VARCHAR2(40 CHAR)     NULL,
  MATERIAL_TYPE                   VARCHAR2(4 CHAR)     NULL,
  MATERIAL_GRP                    VARCHAR2(9 CHAR)     NULL,
  BASE_UOM                        VARCHAR2(3 CHAR)     NULL,
  ORDER_UNIT                      VARCHAR2(3 CHAR)     NULL,
  GROSS_WEIGHT                    NUMBER            NULL,
  NET_WEIGHT                      NUMBER            NULL,
  GROSS_WEIGHT_UNIT               VARCHAR2(3 CHAR)     NULL,
  LENGTH                          NUMBER            NULL,
  WIDTH                           NUMBER            NULL,
  HEIGHT                          NUMBER            NULL,
  DIMENSION_UOM                   VARCHAR2(3 CHAR)     NULL,
  INTERNTL_ARTICLE_NO             VARCHAR2(18 CHAR)     NULL,
  TOTAL_SHELF_LIFE                NUMBER            NULL,
  PRD_SHELF_LIFE_INDCTR           VARCHAR2(1 BYTE)     NULL,
  MARS_INTRMDT_PRDCT_COMPNT_FLAG  VARCHAR2(1 CHAR)     NULL,
  MARS_MERCHANDISING_UNIT_FLAG    VARCHAR2(1 CHAR)     NULL,
  MARS_PRMOTIONAL_MATERIAL_FLAG   VARCHAR2(1 CHAR)     NULL,
  MARS_RETAIL_SALES_UNIT_FLAG     VARCHAR2(1 CHAR)     NULL,
  MARS_SEMI_FINISHED_PRDCT_FLAG   VARCHAR2(1 CHAR)     NULL,
  MARS_RPRSNTTV_ITEM_FLAG         VARCHAR2(1 CHAR)     NULL,
  MARS_TRADED_UNIT_FLAG           VARCHAR2(1 CHAR)     NULL,
  XPLANT_STATUS                   VARCHAR2(2 CHAR)     NULL,
  XPLANT_STATUS_VALID             DATE              NULL,
  BATCH_MNGMNT_REQRMNT_INDCTR     VARCHAR2(2 CHAR)     NULL,
  MARS_PLANT_MATERIAL_TYPE        NUMBER            NULL,
  PROCUREMENT_TYPE                VARCHAR2(1 CHAR)     NULL,
  SPECIAL_PROCUREMENT_TYPE        VARCHAR2(2 CHAR)     NULL,
  ISSUE_STORAGE_LOCATION          VARCHAR2(4 CHAR)     NULL,
  MRP_CONTROLLER                  VARCHAR2(3 CHAR)     NULL,
  PLANT_SPECIFIC_STATUS_VALID     DATE              NULL,
  DELETION_INDCTR                 VARCHAR2(1 CHAR)     NULL,
  PLANT_SPECIFIC_STATUS           VARCHAR2(2 CHAR)     NULL,
  ASSEMBLY_SCRAP_PERCNTG          NUMBER            NULL,
  COMPONENT_SCRAP_PERCNTG         NUMBER            NULL,
  BACKFLUSH_INDCTR                VARCHAR2(1 CHAR)     NULL,
  MARS_RPRSNTTV_ITEM_CODE         VARCHAR2(18 CHAR)     NULL,
  SALES_TEXT_135                  VARCHAR2(4000 CHAR)     NULL,
  SALES_TEXT_147                  VARCHAR2(4000 CHAR)     NULL,
  SALES_TEXT_149                  VARCHAR2(4000 CHAR)     NULL,
  SALES_TEXT_163                  VARCHAR2(4000 CHAR)     NULL,
  SALES_TEXT_164                  VARCHAR2(4000 CHAR)     NULL,
  SALES_TEXT_234                  VARCHAR2(4000 CHAR)     NULL,
  REGIONAL_CODE_8                 VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_10                VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_14                VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_17                VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_18                VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_19                VARCHAR2(18 CHAR)     NULL,
  REGIONAL_CODE_20                VARCHAR2(18 CHAR)     NULL,
  BDS_UNIT_COST                   NUMBER            NULL,
  FUTURE_PLANNED_PRICE_1          NUMBER            NULL,
  VLTN_CLASS                      VARCHAR2(4 CHAR)     NULL,
  BDS_PCE_FACTOR_FROM_BASE_UOM    NUMBER            NULL,
  MARS_PCE_ITEM_CODE              VARCHAR2(18 CHAR)     NULL,
  MARS_PCE_INTERNTL_ARTICLE_NO    VARCHAR2(18 CHAR)     NULL,
  BDS_SB_FACTOR_FROM_BASE_UOM     NUMBER            NULL,
  MARS_SB_ITEM_CODE               VARCHAR2(18 CHAR)     NULL,
  DISCONTINUATION_INDCTR          VARCHAR2(1 CHAR)     NULL,
  FOLLOWUP_MATERIAL               VARCHAR2(18 CHAR)     NULL,
  MATERIAL_DIVISION               VARCHAR2(2 CHAR)     NULL,
  MRP_TYPE                        VARCHAR2(2 CHAR)     NULL,
  MAX_STORAGE_PRD                 NUMBER            NULL,
  MAX_STORAGE_PRD_UNIT            VARCHAR2(3 CHAR)     NULL,
  ISSUE_UNIT                      VARCHAR2(3 CHAR)     NULL,
  PLANNED_DELIVERY_DAYS           NUMBER            NULL,
  EFFECTIVE_OUT_DATE              DATE              NULL,
  MSG_TIMESTAMP                   VARCHAR2(14 BYTE)     NULL,
  MARS_SHPPING_CONTNR_FLAG        VARCHAR2(1 CHAR)     NULL,
  MARS_PLAN_ITEM_FLAG             VARCHAR2(6 CHAR)     NULL,
  DELETION_FLAG                   VARCHAR2(1 CHAR)     NULL,
  VLTN_DELETION_INDCTR            VARCHAR2(1 CHAR)     NULL,
  PLANT_DELETION_INDCTR           VARCHAR2(1 CHAR)     NULL
)
TABLESPACE BDS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX01  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX01 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(MATERIAL_TYPE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX02  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX02 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(PLANT_CODE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX03  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX03 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(PROCUREMENT_TYPE, SPECIAL_PROCUREMENT_TYPE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX04  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX04 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(MARS_PLANT_MATERIAL_TYPE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX05  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX05 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(PLANT_CODE, SAP_MATERIAL_CODE, PLANT_SPECIFIC_STATUS, MATERIAL_DIVISION, MATERIAL_TYPE, 
MARS_TRADED_UNIT_FLAG, MRP_TYPE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX06  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX06 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(PLANT_CODE, MATERIAL_TYPE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX07  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX07 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(MARS_TRADED_UNIT_FLAG)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX08  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX08 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(MARS_RETAIL_SALES_UNIT_FLAG)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_IDX09  (Index) 
--
CREATE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_IDX09 ON BDS.BDS_MATERIAL_PLANT_LOCAL
(MARS_INTRMDT_PRDCT_COMPNT_FLAG)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL_PK  (Index) 
--
CREATE UNIQUE INDEX BDS.BDS_MATERIAL_PLANT_LOCAL_PK ON BDS.BDS_MATERIAL_PLANT_LOCAL
(SAP_MATERIAL_CODE, PLANT_CODE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- BDS_MATERIAL_PLANT_LOCAL  (Synonym) 
--
CREATE PUBLIC SYNONYM BDS_MATERIAL_PLANT_LOCAL FOR BDS.BDS_MATERIAL_PLANT_LOCAL;


-- 
-- Non Foreign Key Constraints for Table BDS_MATERIAL_PLANT_LOCAL 
-- 
ALTER TABLE BDS.BDS_MATERIAL_PLANT_LOCAL ADD (
  CONSTRAINT BDS_MATERIAL_PLANT_LOCAL_PK
 PRIMARY KEY
 (SAP_MATERIAL_CODE, PLANT_CODE)
    USING INDEX 
    TABLESPACE BDS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          256K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO APPSUPPORT;

GRANT DELETE, INSERT, SELECT, UPDATE ON BDS.BDS_MATERIAL_PLANT_LOCAL TO BDS_APP WITH GRANT OPTION;

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO ICS_READER;

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO MANU WITH GRANT OPTION;

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO MANU_APP WITH GRANT OPTION;

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO PT_APP;

GRANT SELECT ON BDS.BDS_MATERIAL_PLANT_LOCAL TO SITE_APP;
