-- Create a sequence for FFLU Data Loads
CREATE SEQUENCE  "FFLU"."FFLU_LOAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

grant select on "FFLU"."FFLU_LOAD_SEQ" to fflu_app;