DROP VIEW MANU_APP.ICS_MATL_VW;

/* Formatted on 2008/10/01 09:01 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW manu_app.ics_matl_vw (matl_code,
                                                   matl_desc,
                                                   plant,
                                                   matl_type,
                                                   matl_group,
                                                   rgnl_code_nmbr,
                                                   base_uom,
                                                   order_uom,
                                                   gross_wght,
                                                   net_wght,
                                                   dclrd_uom,
                                                   lngth,
                                                   width,
                                                   hght,
                                                   uom_for_lwh,
                                                   ean_code,
                                                   shelf_life,
                                                   intrmdt_prdct_cmpnnt,
                                                   mrchndsng_unit,
                                                   prmtnl_matl,
                                                   rtl_sales_unit,
                                                   semi_fnshd_prdct,
                                                   rprsnttv_item,
                                                   trdd_unit,
                                                   plant_orntd_matl_type,
                                                   unit_cost,
                                                   batch_mngmnt_rqrmnt_indctr,
                                                   prcrmnt_type,
                                                   spcl_prcrmnt_type,
                                                   issue_strg_locn,
                                                   mrp_cntrllr,
                                                   plant_sts_start,
                                                   x_plant_matl_sts,
                                                   x_plant_matl_sts_start,
                                                   dltn_indctr,
                                                   plant_sts,
                                                   assy_scrap,
                                                   comp_scrap,
                                                   plnd_price,
                                                   vltn_class,
                                                   back_flush_ind,
                                                   brand_flag_code,
                                                   brand_flag_long_desc,
                                                   rprsnttv_item_code,
                                                   matl_sales_text
                                                  )
AS
  SELECT LTRIM (t01.sap_material_code, '0') AS matl_code,
         t01.bds_material_desc_en AS matl_desc, t01.plant_code AS plant,
         t01.material_type AS matl_type, t01.material_grp AS matl_group,
         LTRIM (DECODE (t01.regional_code_17,
                        '*NONE', NULL,
                        t01.regional_code_17
                       ),
                '0'
               ) AS rgnl_code_nmbr,
         t01.base_uom, t01.order_unit AS order_uom,
         t01.gross_weight AS gross_wght, t01.net_weight AS net_wght,
         t01.gross_weight_unit AS dclrd_uom, t01.LENGTH AS lngth, t01.width,
         t01.height AS hght, t01.dimension_uom AS uom_for_lwh,
         t01.interntl_article_no AS ean_code,
         t01.total_shelf_life AS shelf_life,
         t01.mars_intrmdt_prdct_compnt_flag AS intrmdt_prdct_cmpnnt,
         t01.mars_merchandising_unit_flag AS mrchndsng_unit,
         t01.mars_prmotional_material_flag AS prmtnl_matl,
         t01.mars_retail_sales_unit_flag AS rtl_sales_unit,
         t01.mars_semi_finished_prdct_flag AS semi_fnshd_prdct,
         t01.mars_rprsnttv_item_flag AS rprsnttv_item,
         t01.mars_traded_unit_flag AS trdd_unit,
         t01.mars_plant_material_type AS plant_orntd_matl_type,
         TO_CHAR (t01.bds_unit_cost) AS unit_cost,
         t01.batch_mngmnt_reqrmnt_indctr AS batch_mngmnt_rqrmnt_indctr,
         t01.procurement_type AS prcrmnt_type,
         t01.special_procurement_type AS spcl_prcrmnt_type,
         t01.issue_storage_location AS issue_strg_locn,
         t01.mrp_controller AS mrp_cntrllr,
         t01.plant_specific_status_valid AS plant_sts_start,
         t01.xplant_status AS x_plant_matl_sts,
         DECODE (t01.xplant_status_valid,
                 NULL, TO_DATE ('01/01/1900', 'dd/mm/yyyy'),
                 xplant_status_valid
                ) AS x_plant_matl_sts_start,
         t01.deletion_indctr AS dltn_indctr,
         t01.plant_specific_status AS plant_sts,
         t01.assembly_scrap_percntg AS assy_scrap,
         t01.component_scrap_percntg AS comp_scrap,
         t01.future_planned_price_1 AS plnd_price, t01.vltn_class,
         t01.backflush_indctr AS back_flush_ind,
         t02.sap_brand_flag_code AS brand_flag_code,
         t03.sap_charistic_value_long_desc AS brand_flag_long_desc,
         LTRIM (t01.mars_rprsnttv_item_code, '0') AS rprsnttv_item_code,
         t01.sales_text_147 AS matl_sales_text
    FROM bds_material_plant_mfanz t01,
         bds_material_classfctn_ics t02,
         bds_refrnc_charistic_ics t03
   WHERE t01.sap_material_code = t02.sap_material_code(+)
     AND t02.sap_brand_flag_code = t03.sap_charistic_value_code(+)
     AND t03.sap_charistic_code = '/MARS/MD_CHC003'
     AND t01.plant_code IN ('AU20', 'AU21', 'AU22', 'AU23', 'AU24', 'AU25');


