DROP VIEW MANU_APP.ICS_MATL;

/* Formatted on 2008/10/01 09:01 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW manu_app.ics_matl (matl_code,
                                                matl_desc,
                                                plant,
                                                matl_type,
                                                matl_group,
                                                rgnl_code_nmbr,
                                                base_uom,
                                                order_uom,
                                                gross_wght,
                                                net_wght,
                                                dclrd_uom,
                                                lngth,
                                                width,
                                                hght,
                                                uom_for_lwh,
                                                ean_code,
                                                shelf_life,
                                                intrmdt_prdct_cmpnnt,
                                                mrchndsng_unit,
                                                prmtnl_matl,
                                                rtl_sales_unit,
                                                semi_fnshd_prdct,
                                                rprsnttv_item,
                                                trdd_unit,
                                                plant_orntd_matl_type,
                                                unit_cost,
                                                batch_mngmnt_rqrmnt_indctr,
                                                prcrmnt_type,
                                                spcl_prcrmnt_type,
                                                issue_strg_locn,
                                                mrp_cntrllr,
                                                plant_sts_start,
                                                x_plant_matl_sts,
                                                x_plant_matl_sts_start,
                                                dltn_indctr,
                                                plant_sts,
                                                assy_scrap,
                                                comp_scrap,
                                                plnd_price,
                                                vltn_class,
                                                back_flush_ind
                                               )
AS
  SELECT LTRIM (sap_material_code, '0') AS matl_code,
         bds_material_desc_en AS matl_desc, plant_code AS plant,
         material_type AS matl_type, material_grp AS matl_group,
         LTRIM (DECODE (regional_code_17, '*NONE', NULL, regional_code_17),
                '0'
               ) AS rgnl_code_nmbr,
         base_uom, order_unit AS order_uom, gross_weight AS gross_wght,
         net_weight AS net_wght, gross_weight_unit AS dclrd_uom,
         LENGTH AS lngth, width, height AS hght, dimension_uom AS uom_for_lwh,
         interntl_article_no AS ean_code, total_shelf_life AS shelf_life,
         mars_intrmdt_prdct_compnt_flag AS intrmdt_prdct_cmpnnt,
         mars_merchandising_unit_flag AS mrchndsng_unit,
         mars_prmotional_material_flag AS prmtnl_matl,
         mars_retail_sales_unit_flag AS rtl_sales_unit,
         mars_semi_finished_prdct_flag AS semi_fnshd_prdct,
         mars_rprsnttv_item_flag AS rprsnttv_item,
         mars_traded_unit_flag AS trdd_unit,
         mars_plant_material_type AS plant_orntd_matl_type,
         TO_CHAR (bds_unit_cost) AS unit_cost,
         batch_mngmnt_reqrmnt_indctr AS batch_mngmnt_rqrmnt_indctr,
         procurement_type AS prcrmnt_type,
         special_procurement_type AS spcl_prcrmnt_type,
         issue_storage_location AS issue_strg_locn,
         mrp_controller AS mrp_cntrllr,
         plant_specific_status_valid AS plant_sts_start,
         xplant_status AS x_plant_matl_sts,
         DECODE (xplant_status_valid,
                 NULL, TO_DATE ('01/01/1900', 'dd/mm/yyyy'),
                 xplant_status_valid
                ) AS x_plant_matl_sts_start,
         deletion_indctr AS dltn_indctr, plant_specific_status AS plant_sts,
         assembly_scrap_percntg AS assy_scrap,
         component_scrap_percntg AS comp_scrap,
         future_planned_price_1 AS plnd_price, vltn_class,
         backflush_indctr AS back_flush_ind
    FROM bds_material_plant_mfanz a
   WHERE plant_code IN ('AU20', 'AU21', 'AU22', 'AU23', 'AU24', 'AU25');


