/* Formatted on 15-Jul-2011 11:30:03 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW MANU_APP.PM_EQUIPMENT_VW
(
   SAP_EQUIPMENT_CODE,
   EQUIPMENT_DESC,
   FUNCTNL_LOCN_CODE,
   SORT_FIELD,
   PLANT_CODE
)
AS
   SELECT sap_equipment_code,
          equipment_desc,
          functnl_locn_code,
          sort_field,
          plant_code
     FROM bds_equipment_plant_hdr;

COMMENT ON TABLE MANU_APP.PM_EQUIPMENT_VW IS 'Plant Maintenance Equipment';

COMMENT ON COLUMN MANU_APP.PM_EQUIPMENT_VW.SAP_EQUIPMENT_CODE IS 'Equipment Code (ITOB-EQUNR)';

COMMENT ON COLUMN MANU_APP.PM_EQUIPMENT_VW.EQUIPMENT_DESC IS 'Equipment Description (ITOB-EQKTX)';

COMMENT ON COLUMN MANU_APP.PM_EQUIPMENT_VW.FUNCTNL_LOCN_CODE IS 'Functional Location Name (ITOB-TPLNR)';

COMMENT ON COLUMN MANU_APP.PM_EQUIPMENT_VW.SORT_FIELD IS 'Sort Field (ITOB-EQFNR)';

COMMENT ON COLUMN MANU_APP.PM_EQUIPMENT_VW.PLANT_CODE IS 'Plant Code (calculated in the hub)';


CREATE PUBLIC SYNONYM PM_EQUIPMENT_VW FOR MANU_APP.PM_EQUIPMENT_VW;


GRANT SELECT ON MANU_APP.PM_EQUIPMENT_VW TO APPSUPPORT;

GRANT SELECT ON MANU_APP.PM_EQUIPMENT_VW TO MANU_MAINT;

GRANT SELECT ON MANU_APP.PM_EQUIPMENT_VW TO MANU_USER;
