/******************************************************************************/
/* View Definition                                                            */
/******************************************************************************/
/**
 Object : material_jp_sku_view
 Owner  : dw_app

 DESCRIPTION
 -----------
 Data Warehouse - View

 YYYY/MM   Author         Description
 -------   ------         -----------
 2004/11   Steve Gregan   Created

*******************************************************************************/

/*-*/
/* View creation
/*-*/
create or replace force view dw_app.material_jp_sku_view
   (SAP_MATERIAL_CODE,
    MATERIAL_DESC_EN,
    MATERIAL_DESC_JA,
    MATERIAL_STS_CODE, 
    MATERIAL_STS_ABBRD_DESC,
    MATERIAL_STS_DESC,
    GROSS_WGT,
    NET_WGT,
    SAP_WGT_UNIT_CODE, 
    WGT_UNIT_ABBRD_DESC,
    WGT_UNIT_DESC,
    VOL,
    SAP_VOL_UNIT_CODE,
    VOL_UNIT_ABBRD_DESC, 
    VOL_UNIT_DESC,
    SAP_BASE_UOM_CODE,
    BASE_UOM_ABBRD_DESC,
    BASE_UOM_DESC,
    MATERIAL_OWNER, 
    MAT_LEAD_TIME_DAYS,
    OLD_MATERIAL_CODE,
    MATERIAL_TYPE_FLAG_INT,
    MATERIAL_TYPE_FLAG_RSU, 
    MATERIAL_TYPE_FLAG_TDU,
    MATERIAL_TYPE_FLAG_MCU,
    MATERIAL_TYPE_FLAG_PRO,
    MATERIAL_TYPE_FLAG_SFP,
    MATERIAL_TYPE_FLAG_SC, 
    MATERIAL_TYPE_FLAG_REP,
    EAN_UPC,
    SAP_EAN_UPC_CTGRY_CODE,
    EAN_UPC_CTGRY_DESC,
    SAP_MATERIAL_DIVISION_CODE, 
    MATERIAL_DIVISION_DESC,
    SAP_MATERIAL_TYPE_CODE,
    MATERIAL_TYPE_DESC,
    SAP_MATERIAL_GRP_CODE,
    MATERIAL_GRP_DESC, 
    SAP_MATERIAL_GRP_PACKS_CODE,
    MATERIAL_GRP_PACKS_DESC,
    SAP_CROSS_PLANT_MATL_STS_CODE,
    CROSS_PLANT_MATL_STS_DESC,
    SAP_BUS_SGMNT_CODE, 
    BUS_SGMNT_ABBRD_DESC,
    BUS_SGMNT_DESC,
    SAP_MKT_SGMNT_CODE,
    MKT_SGMNT_ABBRD_DESC,
    MKT_SGMNT_DESC, 
    SAP_BRAND_ESSNC_CODE,
    BRAND_ESSNC_ABBRD_DESC,
    BRAND_ESSNC_DESC,
    SAP_BRAND_FLAG_CODE,
    BRAND_FLAG_ABBRD_DESC, 
    BRAND_FLAG_DESC,
    SAP_BRAND_SUB_FLAG_CODE,
    BRAND_SUB_FLAG_ABBRD_DESC,
    BRAND_SUB_FLAG_DESC,
    SAP_SUPPLY_SGMNT_CODE, 
    SUPPLY_SGMNT_ABBRD_DESC,
    SUPPLY_SGMNT_DESC,
    SAP_INGRED_VRTY_CODE,
    INGRED_VRTY_ABBRD_DESC,
    INGRED_VRTY_DESC, 
    SAP_FUNCL_VRTY_CODE,
    FUNCL_VRTY_ABBRD_DESC,
    FUNCL_VRTY_DESC,
    SAP_MAJOR_PACK_CODE,
    MAJOR_PACK_ABBRD_DESC, 
    MAJOR_PACK_DESC,
    SAP_MINOR_PACK_CODE,
    MINOR_PACK_ABBRD_DESC,
    MINOR_PACK_DESC,
    SAP_MULTI_PACK_QTY_CODE, 
    MULTI_PACK_QTY_ABBRD_DESC,
    MULTI_PACK_QTY_DESC,
    SAP_OCCSN_CODE,
    OCCSN_ABBRD_DESC,
    OCCSN_DESC, 
    SAP_PRDCT_CTGRY_CODE,
    PRDCT_CTGRY_ABBRD_DESC,
    PRDCT_CTGRY_DESC,
    SAP_PRDCT_TYPE_CODE,
    PRDCT_TYPE_ABBRD_DESC, 
    PRDCT_TYPE_DESC,
    SAP_PRDCT_PACK_SIZE_CODE,
    PRDCT_PACK_SIZE_ABBRD_DESC,
    PRDCT_PACK_SIZE_DESC,
    SAP_CNSMR_PACK_FRMT_CODE, 
    CNSMR_PACK_FRMT_ABBRD_DESC,
    CNSMR_PACK_FRMT_DESC,
    SAP_PACK_TYPE_CODE,
    PACK_TYPE_ABBRD_DESC,
    PACK_TYPE_DESC, 
    SAP_PRDCT_SIZE_GRP_CODE,
    PRDCT_SIZE_GRP_ABBRD_DESC,
    PRDCT_SIZE_GRP_DESC,
    SAP_PRIM_CNSMPTN_GRP_CODE,
    PRIM_CNSMPTN_GRP_ABBRD_DESC, 
    PRIM_CNSMPTN_GRP_DESC,
    SAP_TRAD_UNIT_FRMT_CODE,
    TRAD_UNIT_FRMT_ABBRD_DESC,
    TRAD_UNIT_FRMT_DESC,
    SAP_TRAD_UNIT_CONFIG_CODE, 
    TRAD_UNIT_CONFIG_ABBRD_DESC,
    TRAD_UNIT_CONFIG_DESC,
    SAP_ONPACK_CNSMR_VALUE_CODE,
    ONPACK_CNSMR_VALUE_ABBRD_DESC,
    ONPACK_CNSMR_VALUE_DESC, 
    SAP_ONPACK_CNSMR_OFFER_CODE,
    ONPACK_CNSMR_OFFER_ABBRD_DESC,
    ONPACK_CNSMR_OFFER_DESC,
    SAP_ONPACK_TRADE_OFFER_CODE,
    ONPACK_TRADE_OFFER_ABBRD_DESC, 
    ONPACK_TRADE_OFFER_DESC,
    SAP_REP_ITEM_CODE,
    REP_ITEM_DESC_EN,
    REP_ITEM_DESC_JA) AS 
   SELECT "SAP_MATERIAL_CODE",
          "MATERIAL_DESC_EN",
          "MATERIAL_DESC_JA",
          "MATERIAL_STS_CODE",
          "MATERIAL_STS_ABBRD_DESC",
          "MATERIAL_STS_DESC",
          "GROSS_WGT",
          "NET_WGT",
          "SAP_WGT_UNIT_CODE",
          "WGT_UNIT_ABBRD_DESC",
          "WGT_UNIT_DESC",
          "VOL",
          "SAP_VOL_UNIT_CODE",
          "VOL_UNIT_ABBRD_DESC",
          "VOL_UNIT_DESC",
          "SAP_BASE_UOM_CODE",
          "BASE_UOM_ABBRD_DESC",
          "BASE_UOM_DESC",
          "MATERIAL_OWNER",
          "MAT_LEAD_TIME_DAYS",
          "OLD_MATERIAL_CODE",
          "MATERIAL_TYPE_FLAG_INT",
          "MATERIAL_TYPE_FLAG_RSU",
          "MATERIAL_TYPE_FLAG_TDU",
          "MATERIAL_TYPE_FLAG_MCU",
          "MATERIAL_TYPE_FLAG_PRO",
          "MATERIAL_TYPE_FLAG_SFP",
          "MATERIAL_TYPE_FLAG_SC",
          "MATERIAL_TYPE_FLAG_REP",
          "EAN_UPC",
          "SAP_EAN_UPC_CTGRY_CODE",
          "EAN_UPC_CTGRY_DESC",
          "SAP_MATERIAL_DIVISION_CODE",
          "MATERIAL_DIVISION_DESC",
          "SAP_MATERIAL_TYPE_CODE",
          "MATERIAL_TYPE_DESC",
          "SAP_MATERIAL_GRP_CODE",
          "MATERIAL_GRP_DESC",
          "SAP_MATERIAL_GRP_PACKS_CODE",
          "MATERIAL_GRP_PACKS_DESC",
          "SAP_CROSS_PLANT_MATL_STS_CODE",
          "CROSS_PLANT_MATL_STS_DESC",
          "SAP_BUS_SGMNT_CODE",
          "BUS_SGMNT_ABBRD_DESC",
          "BUS_SGMNT_DESC",
          "SAP_MKT_SGMNT_CODE",
          "MKT_SGMNT_ABBRD_DESC",
          "MKT_SGMNT_DESC",
          "SAP_BRAND_ESSNC_CODE",
          "BRAND_ESSNC_ABBRD_DESC",
          "BRAND_ESSNC_DESC",
          "SAP_BRAND_FLAG_CODE",
          "BRAND_FLAG_ABBRD_DESC",
          "BRAND_FLAG_DESC",
          "SAP_BRAND_SUB_FLAG_CODE",
          "BRAND_SUB_FLAG_ABBRD_DESC",
          "BRAND_SUB_FLAG_DESC",
          "SAP_SUPPLY_SGMNT_CODE",
          "SUPPLY_SGMNT_ABBRD_DESC",
          "SUPPLY_SGMNT_DESC",
          "SAP_INGRED_VRTY_CODE",
          "INGRED_VRTY_ABBRD_DESC",
          "INGRED_VRTY_DESC",
          "SAP_FUNCL_VRTY_CODE",
          "FUNCL_VRTY_ABBRD_DESC",
          "FUNCL_VRTY_DESC",
          "SAP_MAJOR_PACK_CODE",
          "MAJOR_PACK_ABBRD_DESC",
          "MAJOR_PACK_DESC",
          "SAP_MINOR_PACK_CODE",
          "MINOR_PACK_ABBRD_DESC",
          "MINOR_PACK_DESC",
          "SAP_MULTI_PACK_QTY_CODE",
          "MULTI_PACK_QTY_ABBRD_DESC",
          "MULTI_PACK_QTY_DESC",
          "SAP_OCCSN_CODE",
          "OCCSN_ABBRD_DESC",
          "OCCSN_DESC",
          "SAP_PRDCT_CTGRY_CODE",
          "PRDCT_CTGRY_ABBRD_DESC",
          "PRDCT_CTGRY_DESC",
          "SAP_PRDCT_TYPE_CODE",
          "PRDCT_TYPE_ABBRD_DESC",
          "PRDCT_TYPE_DESC",
          "SAP_PRDCT_PACK_SIZE_CODE",
          "PRDCT_PACK_SIZE_ABBRD_DESC",
          "PRDCT_PACK_SIZE_DESC",
          "SAP_CNSMR_PACK_FRMT_CODE",
          "CNSMR_PACK_FRMT_ABBRD_DESC",
          "CNSMR_PACK_FRMT_DESC",
          "SAP_PACK_TYPE_CODE",
          "PACK_TYPE_ABBRD_DESC",
          "PACK_TYPE_DESC",
          "SAP_PRDCT_SIZE_GRP_CODE",
          "PRDCT_SIZE_GRP_ABBRD_DESC",
          "PRDCT_SIZE_GRP_DESC",
          "SAP_PRIM_CNSMPTN_GRP_CODE",
          "PRIM_CNSMPTN_GRP_ABBRD_DESC",
          "PRIM_CNSMPTN_GRP_DESC",
          "SAP_TRAD_UNIT_FRMT_CODE",
          "TRAD_UNIT_FRMT_ABBRD_DESC",
          "TRAD_UNIT_FRMT_DESC",
          "SAP_TRAD_UNIT_CONFIG_CODE",
          "TRAD_UNIT_CONFIG_ABBRD_DESC",
          "TRAD_UNIT_CONFIG_DESC",
          "SAP_ONPACK_CNSMR_VALUE_CODE",
          "ONPACK_CNSMR_VALUE_ABBRD_DESC",
          "ONPACK_CNSMR_VALUE_DESC",
          "SAP_ONPACK_CNSMR_OFFER_CODE",
          "ONPACK_CNSMR_OFFER_ABBRD_DESC",
          "ONPACK_CNSMR_OFFER_DESC",
          "SAP_ONPACK_TRADE_OFFER_CODE",
          "ONPACK_TRADE_OFFER_ABBRD_DESC",
          "ONPACK_TRADE_OFFER_DESC",
          "SAP_REP_ITEM_CODE",
          "REP_ITEM_DESC_EN",
          "REP_ITEM_DESC_JA"
     FROM (SELECT *
             FROM DD.MATERIAL_DIM
            WHERE MATERIAL_TYPE_DESC IN ('Finished products', 'Raw material & Raw SFG'))
    WHERE MATERIAL_TYPE_FLAG_TDU = 'Y' AND MATERIAL_DESC_JA IS NOT NULL OR 
          MATERIAL_TYPE_FLAG_INT = 'Y' AND MATERIAL_DESC_JA IS NOT NULL OR
          MATERIAL_TYPE_FLAG_SFP = 'Y' AND MATERIAL_DESC_JA IS NOT NULL;

/*-*/
/* Authority
/*-*/
grant select on dw_app.material_jp_sku_view to bo_user;

/*-*/
/* Synonym
/*-*/
create or replace public synonym material_jp_sku_view for dw_app.material_jp_sku_view;
