<html>
<head>
   <meta http-equiv="content-type" content="text/html">
   <link rel="stylesheet" type="text/css" href="ics_style.css">
</head>
<body class="clsBody02" scroll="auto" onLoad="parent.setHelp('ics_fatal_help.htm');parent.setMenuHeading('&nbsp;');parent.showMenu();">                   
   <table align=center valign=center border=0 cellpadding=0 cellspacing=0 cols=1 width=100%>
      <tr>
         <td class="clsHome" align=center nowrap><nobr>FATAL ERROR</nobr></td>
      </tr>
      <tr>
         <td class="clsLabelBB" align=center>&nbsp;</td>
      </tr>
      <tr>
         <td class="clsLabelBB" align=center>&nbsp;<%=strReturn%>&nbsp;</td>
      </tr>
   </table>
</body>
</html>