ALTER TABLE CR.CARE_XREF
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.CARE_XREF CASCADE CONSTRAINTS;

CREATE TABLE CR.CARE_XREF
(
  XRF_TDU     VARCHAR2(18 BYTE)                 NOT NULL,
  XRF_KEY     VARCHAR2(64 BYTE)                 NOT NULL,
  XRF_RSU     VARCHAR2(10 BYTE)                 NOT NULL,
  XRF_STATUS  VARCHAR2(1 BYTE)
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.CARE_XREF IS 'AP CARE Cross Reference';

COMMENT ON COLUMN CR.CARE_XREF.XRF_TDU IS 'Traded Unit (GRD Material Code)';

COMMENT ON COLUMN CR.CARE_XREF.XRF_KEY IS 'TDU to RSU relationship (Characteristic Join)';

COMMENT ON COLUMN CR.CARE_XREF.XRF_RSU IS 'Representative Retail Sales Unit (GRD Material Code)';


CREATE INDEX CR.CARE_XREF_IDX01 ON CR.CARE_XREF
(XRF_STATUS, XRF_RSU)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CR.CARE_XREF_PK ON CR.CARE_XREF
(XRF_TDU, XRF_KEY)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM CARE_XREF;

CREATE PUBLIC SYNONYM CARE_XREF FOR CR.CARE_XREF;


ALTER TABLE CR.CARE_XREF ADD (
  CONSTRAINT CARE_XREF_PK
 PRIMARY KEY
 (XRF_TDU, XRF_KEY)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.CARE_XREF TO CR_APP WITH GRANT OPTION;

