DROP TABLE CR.CARE_TDU_TMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE CR.CARE_TDU_TMP
(
  GRD_TDU                VARCHAR2(18 CHAR),
  XRF_KEY                VARCHAR2(64 CHAR),
  KEYW_TYPE              VARCHAR2(10 CHAR),
  KEYW_DESCRIPTION_40    VARCHAR2(40 CHAR),
  KEYW_DESCRIPTION_74    VARCHAR2(74 CHAR),
  KEYW_ASK_FOR_INPUT     VARCHAR2(1 CHAR),
  KEYW_APN               VARCHAR2(20 CHAR),
  KEYW_REPLACE_KEY       VARCHAR2(1 CHAR),
  KEYW_INACTIVE          VARCHAR2(1 CHAR),
  KEYW_AT_END            VARCHAR2(1 CHAR),
  KEYW_KEYWORD_01        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_01_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_01_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_02        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_02_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_02_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_03        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_03_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_03_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_04        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_04_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_04_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_05        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_05_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_05_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_06        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_06_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_06_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_07        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_07_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_07_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_08        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_08_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_08_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_09        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_09_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_09_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_10        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_10_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_10_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_11        VARCHAR2(10 CHAR),
  KEYW_KEYWORD_11_DESC   VARCHAR2(40 CHAR),
  KEYW_KEYWORD_11_DESCL  VARCHAR2(74 CHAR),
  KEYW_KEYWORD_12        VARCHAR2(10 CHAR),
  KEYW_MISC1_X           VARCHAR2(10 CHAR),
  KEYW_MISC2             VARCHAR2(10 CHAR),
  KEYW_MISC3             VARCHAR2(10 CHAR)
)
ON COMMIT PRESERVE ROWS
NOCACHE;

COMMENT ON TABLE CR.CARE_TDU_TMP IS '[GLBL TMP TABLE] AP Care - TDU data load';


CREATE INDEX CR.CARE_TDU_TMP_IDX01 ON CR.CARE_TDU_TMP
(GRD_TDU, XRF_KEY);


DROP PUBLIC SYNONYM CARE_TDU_TMP;

CREATE PUBLIC SYNONYM CARE_TDU_TMP FOR CR.CARE_TDU_TMP;


GRANT DELETE, INSERT, SELECT, UPDATE ON CR.CARE_TDU_TMP TO CR_APP WITH GRANT OPTION;

