ALTER TABLE CR.CARE_TDU_TMP
 ADD (KEYW_KEYWORD_10_DESC  VARCHAR2(40 CHAR));

ALTER TABLE CR.CARE_TDU_TMP
 ADD (KEYW_KEYWORD_10_DESCL  VARCHAR2(74 CHAR));

ALTER TABLE CR.CARE_TDU_TMP
 ADD (KEYW_KEYWORD_11_DESC  VARCHAR2(40 CHAR));

ALTER TABLE CR.CARE_TDU_TMP
 ADD (KEYW_KEYWORD_11_DESCL  VARCHAR2(74 CHAR));

