ALTER TABLE CR.CODE_LOOKUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.CODE_LOOKUP CASCADE CONSTRAINTS;

CREATE TABLE CR.CODE_LOOKUP
(
  XRF_TYPE  VARCHAR2(32 BYTE)                   NOT NULL,
  XRF_SRC   VARCHAR2(128 BYTE)                  NOT NULL,
  XRF_TRG   VARCHAR2(128 BYTE)
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.CODE_LOOKUP IS 'AP CARE Generic Lookup';

COMMENT ON COLUMN CR.CODE_LOOKUP.XRF_TYPE IS 'Lookup Type';

COMMENT ON COLUMN CR.CODE_LOOKUP.XRF_SRC IS 'Lookup Source';

COMMENT ON COLUMN CR.CODE_LOOKUP.XRF_TRG IS 'Lookup Target';


CREATE UNIQUE INDEX CR.CODE_LOOKUP_PK ON CR.CODE_LOOKUP
(XRF_TYPE, XRF_SRC)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM CODE_LOOKUP;

CREATE PUBLIC SYNONYM CODE_LOOKUP FOR CR.CODE_LOOKUP;


ALTER TABLE CR.CODE_LOOKUP ADD (
  CONSTRAINT CODE_LOOKUP_PK
 PRIMARY KEY
 (XRF_TYPE, XRF_SRC)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.CODE_LOOKUP TO CR_APP WITH GRANT OPTION;

