ALTER TABLE CR.GRD_MAT_DET
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.GRD_MAT_DET CASCADE CONSTRAINTS;

CREATE TABLE CR.GRD_MAT_DET
(
  MATNR      VARCHAR2(18 CHAR)                  NOT NULL,
  USAGECODE  VARCHAR2(3 CHAR)                   NOT NULL,
  ORGENTITY  VARCHAR2(4 CHAR)                   NOT NULL,
  STARTDATE  VARCHAR2(8 CHAR),
  ENDDATE    VARCHAR2(8 CHAR)
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.GRD_MAT_DET IS 'GRD Material Detail';

COMMENT ON COLUMN CR.GRD_MAT_DET.MATNR IS 'Material Number';

COMMENT ON COLUMN CR.GRD_MAT_DET.USAGECODE IS 'Usage Code';

COMMENT ON COLUMN CR.GRD_MAT_DET.ORGENTITY IS 'Organisational Entity';

COMMENT ON COLUMN CR.GRD_MAT_DET.STARTDATE IS 'Start Date';

COMMENT ON COLUMN CR.GRD_MAT_DET.ENDDATE IS 'End Date';


CREATE UNIQUE INDEX CR.GRD_MAT_DET_PK ON CR.GRD_MAT_DET
(MATNR, USAGECODE, ORGENTITY)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM GRD_MAT_DET;

CREATE PUBLIC SYNONYM GRD_MAT_DET FOR CR.GRD_MAT_DET;


ALTER TABLE CR.GRD_MAT_DET ADD (
  CONSTRAINT GRD_MAT_DET_PK
 PRIMARY KEY
 (MATNR, USAGECODE, ORGENTITY)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.GRD_MAT_DET TO CR_APP WITH GRANT OPTION;

