ALTER TABLE CR.GRD_MAT_LCM
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.GRD_MAT_LCM CASCADE CONSTRAINTS;

CREATE TABLE CR.GRD_MAT_LCM
(
  MATNR        VARCHAR2(18 CHAR)                NOT NULL,
  REGCODE      VARCHAR2(5 BYTE),
  LEGACY_CODE  VARCHAR2(18 CHAR),
  LCMSEQ       NUMBER                           NOT NULL
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.GRD_MAT_LCM IS 'GRD Material Local Code Mapping';

COMMENT ON COLUMN CR.GRD_MAT_LCM.MATNR IS 'Material Number';

COMMENT ON COLUMN CR.GRD_MAT_LCM.REGCODE IS 'Regional Code';

COMMENT ON COLUMN CR.GRD_MAT_LCM.LEGACY_CODE IS 'Legacy Code';


CREATE UNIQUE INDEX CR.GRD_MAT_LCM_PK ON CR.GRD_MAT_LCM
(MATNR, LCMSEQ)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM GRD_MAT_LCM;

CREATE PUBLIC SYNONYM GRD_MAT_LCM FOR CR.GRD_MAT_LCM;


ALTER TABLE CR.GRD_MAT_LCM ADD (
  CONSTRAINT GRD_MAT_LCM_PK
 PRIMARY KEY
 (MATNR, LCMSEQ)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.GRD_MAT_LCM TO CR_APP WITH GRANT OPTION;

