ALTER TABLE CR.GRD_MAT_HDR
 ADD (MKTSGMNT  VARCHAR2(4 CHAR));

ALTER TABLE CR.GRD_MAT_HDR
 ADD (MKTSGMNTDESC  VARCHAR2(12 CHAR));

ALTER TABLE CR.GRD_MAT_HDR
 ADD (MKTSGMNTDESCL  VARCHAR2(30 CHAR));


COMMENT ON COLUMN CR.GRD_MAT_HDR.MKTSGMNT IS 'Market Segment';

COMMENT ON COLUMN CR.GRD_MAT_HDR.MKTSGMNTDESC IS 'Market Segment Desc';

COMMENT ON COLUMN CR.GRD_MAT_HDR.MKTSGMNTDESCL IS 'Market Segment Desc Long';
