ALTER TABLE CR.SALES_DATA_DET
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.SALES_DATA_DET CASCADE CONSTRAINTS;

CREATE TABLE CR.SALES_DATA_DET
(
  SALES_SRC        VARCHAR2(32 CHAR)            NOT NULL,
  SALES_PERIOD     VARCHAR2(6 CHAR)             NOT NULL,
  MATL_CODE        VARCHAR2(18 CHAR)            NOT NULL,
  SALES_TAR        VARCHAR2(32 CHAR)            NOT NULL,
  CASE_QTY         NUMBER,
  PCS_PER_CASE     NUMBER,
  OUTERS_PER_CASE  NUMBER
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.SALES_DATA_DET IS 'Periodic Sales Data - Detail';

COMMENT ON COLUMN CR.SALES_DATA_DET.SALES_SRC IS 'Selling Unit - Source of Sales data';

COMMENT ON COLUMN CR.SALES_DATA_DET.SALES_PERIOD IS 'Mars Period of sales';

COMMENT ON COLUMN CR.SALES_DATA_DET.MATL_CODE IS 'Material Code';

COMMENT ON COLUMN CR.SALES_DATA_DET.SALES_TAR IS 'Sold to market - Target of Sales data (MARKET=*NONE)';

COMMENT ON COLUMN CR.SALES_DATA_DET.CASE_QTY IS 'Number of cases';

COMMENT ON COLUMN CR.SALES_DATA_DET.PCS_PER_CASE IS 'Pieces per Case';

COMMENT ON COLUMN CR.SALES_DATA_DET.OUTERS_PER_CASE IS 'Outers per Case';


CREATE UNIQUE INDEX CR.SALES_DATA_DET_PK ON CR.SALES_DATA_DET
(SALES_SRC, SALES_PERIOD, MATL_CODE, SALES_TAR)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM SALES_DATA_DET;

CREATE PUBLIC SYNONYM SALES_DATA_DET FOR CR.SALES_DATA_DET;


ALTER TABLE CR.SALES_DATA_DET ADD (
  CONSTRAINT SALES_DATA_DET_PK
 PRIMARY KEY
 (SALES_SRC, SALES_PERIOD, MATL_CODE, SALES_TAR)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.SALES_DATA_DET TO CR_APP WITH GRANT OPTION;

