ALTER TABLE CR.SALES_DATA_HDR
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.SALES_DATA_HDR CASCADE CONSTRAINTS;

CREATE TABLE CR.SALES_DATA_HDR
(
  SALES_SRC        VARCHAR2(32 CHAR)            NOT NULL,
  SALES_PERIOD     VARCHAR2(6 CHAR)             NOT NULL,
  SALES_DET_CNT    NUMBER                       NOT NULL,
  XTRCT_TIMESTAMP  VARCHAR2(14 CHAR)            NOT NULL,
  SIL_DATE         DATE                         NOT NULL,
  MATL_CODE_TYPE   VARCHAR2(3 CHAR),
  SOURCE_TYPE      VARCHAR2(3 CHAR)
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.SALES_DATA_HDR IS 'Periodic Sales Data - Header';

COMMENT ON COLUMN CR.SALES_DATA_HDR.SALES_SRC IS 'Selling Unit - Source of Sales data';

COMMENT ON COLUMN CR.SALES_DATA_HDR.SALES_PERIOD IS 'Mars Period of sales';

COMMENT ON COLUMN CR.SALES_DATA_HDR.SALES_DET_CNT IS 'Number of detail lines';

COMMENT ON COLUMN CR.SALES_DATA_HDR.XTRCT_TIMESTAMP IS 'Extract timestamp';

COMMENT ON COLUMN CR.SALES_DATA_HDR.SIL_DATE IS 'Date loaded';

COMMENT ON COLUMN CR.SALES_DATA_HDR.MATL_CODE_TYPE IS 'Material Code Type (GRD or Legacy)';

COMMENT ON COLUMN CR.SALES_DATA_HDR.SOURCE_TYPE IS 'Source Type (FCT or Market)';


CREATE UNIQUE INDEX CR.SALES_DATA_HDR_PK ON CR.SALES_DATA_HDR
(SALES_SRC, SALES_PERIOD)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM SALES_DATA_HDR;

CREATE PUBLIC SYNONYM SALES_DATA_HDR FOR CR.SALES_DATA_HDR;


ALTER TABLE CR.SALES_DATA_HDR ADD (
  CONSTRAINT SALES_DATA_HDR_PK
 PRIMARY KEY
 (SALES_SRC, SALES_PERIOD)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.SALES_DATA_HDR TO CR_APP WITH GRANT OPTION;

