ALTER TABLE CR.SIL_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.SIL_LOG CASCADE CONSTRAINTS;

CREATE TABLE CR.SIL_LOG
(
  LOG_SEQUENCE  NUMBER(15)                      NOT NULL,
  LOG_TRACE     NUMBER(7)                       NOT NULL,
  LOG_TIME      DATE                            NOT NULL,
  LOG_TEXT      VARCHAR2(4000 CHAR)             NOT NULL,
  LOG_SEARCH    VARCHAR2(256 BYTE)
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.SIL_LOG IS 'sil Log Table';

COMMENT ON COLUMN CR.SIL_LOG.LOG_SEQUENCE IS 'Log - log sequence number (sequence generated)';

COMMENT ON COLUMN CR.SIL_LOG.LOG_TRACE IS 'Log - log trace number (incremental)';

COMMENT ON COLUMN CR.SIL_LOG.LOG_TIME IS 'Log - log time';

COMMENT ON COLUMN CR.SIL_LOG.LOG_TEXT IS 'log - log text';

COMMENT ON COLUMN CR.SIL_LOG.LOG_SEARCH IS 'Log - log search';


CREATE UNIQUE INDEX CR.SIL_LOG_PK ON CR.SIL_LOG
(LOG_SEQUENCE, LOG_TRACE)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM SIL_LOG;

CREATE PUBLIC SYNONYM SIL_LOG FOR CR.SIL_LOG;


ALTER TABLE CR.SIL_LOG ADD (
  CONSTRAINT SIL_LOG_PK
 PRIMARY KEY
 (LOG_SEQUENCE, LOG_TRACE)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.SIL_LOG TO CR_APP;

