ALTER TABLE CR.SIL_INTERFACE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CR.SIL_INTERFACE CASCADE CONSTRAINTS;

CREATE TABLE CR.SIL_INTERFACE
(
  INT_INTERFACE    VARCHAR2(32 CHAR)            NOT NULL,
  INT_DESCRIPTION  VARCHAR2(128 CHAR)           NOT NULL,
  INT_FIL_PATH     VARCHAR2(128 CHAR)           NOT NULL,
  INT_EMA_GROUP    VARCHAR2(64 CHAR)            NOT NULL,
  INT_PROCEDURE    VARCHAR2(256 CHAR)           NOT NULL,
  INT_STATUS       VARCHAR2(1 CHAR)             NOT NULL
)
TABLESPACE CR_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CR.SIL_INTERFACE IS 'Care Control System Interface Table';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_INTERFACE IS 'Interface - interface identifier';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_DESCRIPTION IS 'Interface - interface description';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_FIL_PATH IS 'Interface - file path';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_EMA_GROUP IS 'Interface - email group';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_PROCEDURE IS 'Interface - processing procedure';

COMMENT ON COLUMN CR.SIL_INTERFACE.INT_STATUS IS 'Interface - interface status 0=Inactive, 1=Active';


CREATE UNIQUE INDEX CR.SIL_INTERFACE_PK ON CR.SIL_INTERFACE
(INT_INTERFACE)
LOGGING
TABLESPACE CR_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM SIL_INTERFACE;

CREATE PUBLIC SYNONYM SIL_INTERFACE FOR CR.SIL_INTERFACE;


ALTER TABLE CR.SIL_INTERFACE ADD (
  CONSTRAINT SIL_INTERFACE_PK
 PRIMARY KEY
 (INT_INTERFACE)
    USING INDEX 
    TABLESPACE CR_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON CR.SIL_INTERFACE TO CR_APP;

