DROP VIEW MANU.RESOURCES;

/* Formatted on 2008/12/22 11:25 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW manu.resources (resource_code, resource_desc)
AS
  SELECT "RESOURCE_CODE", "RESOURCE_DESC"
    FROM ref_resource;


DROP PUBLIC SYNONYM RESOURCES;

CREATE PUBLIC SYNONYM RESOURCES FOR MANU.RESOURCES;


GRANT SELECT ON MANU.RESOURCES TO MANU_APP WITH GRANT OPTION;

