-- Code to insert new pds_constants for the modified Customer interface package (PDS_CUST_01_PRC)
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('cust_funding','CUST','F','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('gl_level_3','CUST','Level 3','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('gl_level_4','CUST','Level 4','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('gl_level_5','CUST','Level 5','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('level_3','CUST','03','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('level_4','CUST','04','BISHOROB',SYSDATE);
INSERT INTO pds_config.pds_constants (CONST_CODE,CONST_GRP,CONST_VALUE,CONST_LUPDP,CONST_LUPDT) VALUES ('level_5','CUST','05','BISHOROB',SYSDATE);

-- Look at results
SELECT *
FROM pds_config.pds_constants
WHERE CONST_GRP = 'CUST'
ORDER BY const_code;