CREATE OR REPLACE FORCE VIEW "PDS_APP"."PMX_PRICE_EXT_VIEW" ("COCODE", "DIVCODE", "CHANNEL", "PRODCODE", "STARTDATE", "PRICE1", "MNFCOST", "RRP") AS 
  select "COCODE","DIVCODE","CHANNEL","PRODCODE","STARTDATE","PRICE1","MNFCOST","RRP" from lads.test_promax_price_ext_view@ap0064p.world;



CREATE OR REPLACE FORCE VIEW "PDS_APP"."PMX_PRICE_EXT_VIEW" ("COCODE", "DIVCODE", "CHANNEL", "PRODCODE", "STARTDATE", "PRICE1", "MNFCOST", "RRP") AS 
  select "COCODE","DIVCODE","CHANNEL","PRODCODE","STARTDATE","PRICE1","MNFCOST","RRP" from lads.test_promax_price_ext_view@ap0052t.world;

