/******************************************************************************/
/* View Definition                                                            */
/******************************************************************************/
/**
 Object : csv_rpt_0001
 Owner  : bo_user

 DESCRIPTION
 -----------
 Data Warehouse - View

 YYYY/MM   Author         Description
 -------   ------         -----------
 2005/07   Steve Gregan   Created

*******************************************************************************/

/*-*/
/* View creation
/*-*/
create or replace force view bo_user.csv_rpt_0001
   (YEAR_NUM, MONTH_NUM, MONTH_DAY_NUM, SAP_PLANT_CODE, PLANT_DESC, 
 CRPC_PRICE_BAND, GEO_JA_L4, GEO_JA_L5, GEO_JA_L6, SAP_SOLDTO_CODE, 
 SOLDTO_CUST_NAME_JA, SAP_SHIPTO_CODE, SHIPTO_CUST_NAME_JA, BRAND_FLAG_DESC, SUPPLY_SGMNT_DESC, 
 SAP_MATERIAL_CODE, MATERIAL_DESC_JA, BASE_UOM_BILLED_QTY, BPS, NIV, 
 ZCRP, GSV)
AS 
SELECT
  MM.MARS_DATE.YEAR_NUM,
  MM.MARS_DATE.MONTH_NUM,
  MM.MARS_DATE.MONTH_DAY_NUM,
  T1.SAP_PLANT_CODE,
  T1.PLANT_DESC,
  DD.SALES_FACT.CRPC_PRICE_BAND,
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_4, 
    Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_4, 
    Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_4) || '] - No Name Defined' ), 
    DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_4) AS GEO_JA_L4,
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_5, 
    Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_5, 
    Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_5) || '] - No Name Defined' ), 
    DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_5) AS GEO_JA_L5,
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_6, 
    Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_6, 
    Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_6) || '] - No Name Defined' ), 
    DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_6) AS GEO_JA_L6,
  SOLDTO_CUST.SAP_CUST_CODE     AS SAP_SOLDTO_CODE,
  SOLDTO_CUST.CUST_NAME_JA      AS SOLDTO_CUST_NAME_JA,
  DD.CUST_DIM.SAP_CUST_CODE     AS SAP_SHIPTO_CODE,
  DD.CUST_DIM.CUST_NAME_JA      AS SHIPTO_CUST_NAME_JA,
  Decode(Upper(DD.MATERIAL_DIM.BRAND_FLAG_DESC), 
    'NOT APPLICABLE', ' ', DD.MATERIAL_DIM.BRAND_FLAG_DESC)   AS BRAND_FLAG_DESC,
  Decode(Upper(DD.MATERIAL_DIM.SUPPLY_SGMNT_DESC), 
    'NOT APPLICABLE', ' ', DD.MATERIAL_DIM.SUPPLY_SGMNT_DESC) AS SUPPLY_SGMNT_DESC,
  DD.MATERIAL_DIM.SAP_MATERIAL_CODE,
  DD.MATERIAL_DIM.MATERIAL_DESC_JA,
  sum(DD.SALES_FACT.BASE_UOM_BILLED_QTY)       AS BASE_UOM_BILLED_QTY,
  sum(DD.SALES_FACT.SALES_DTL_PRICE_VALUE_2)   AS BPS,
  sum(DD.SALES_FACT.SALES_DTL_PRICE_VALUE_11)  AS NIV,
  sum(DD.SALES_FACT.SALES_DTL_PRICE_VALUE_12)  AS ZCRP,
  sum(DD.SALES_FACT.SALES_DTL_PRICE_VALUE_13)  AS GSV
FROM
  DD.SALES_FORCE_GEO_HIER,
  DD.CUST_DIM  SOLDTO_CUST,
  DD.CUST_DIM,
  DD.MATERIAL_DIM,
  DD.SALES_FACT,
  MM.MARS_DATE,
  DD.SALES_ORG_DIM,
  DD.DISTBN_CHNL_DIM,
  DD.DIVISION_DIM,
  OD.CUST_PARTNER_FUNCN2,
  DD.PLANT_DIM T1
WHERE
  ( DD.SALES_FACT.BILLING_DATE=MM.MARS_DATE.CALENDAR_DATE  )
  AND  ( DD.SALES_FACT.SAP_MATERIAL_CODE=DD.MATERIAL_DIM.SAP_MATERIAL_CODE  )
  AND  ( DD.SALES_FACT.SAP_SALES_DTL_DISTBN_CHNL_CODE=DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE  )
  AND  ( DD.SALES_FACT.SAP_SALES_DTL_DIVISION_CODE=DD.DIVISION_DIM.SAP_DIVISION_CODE  )
  AND  ( DD.SALES_FACT.SAP_SALES_DTL_SALES_ORG_CODE=DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE  )
  AND  ( DD.SALES_FACT.SAP_SHIP_TO_CUST_CODE=DD.CUST_DIM.SAP_CUST_CODE  )
  AND  ( DD.SALES_FACT.SAP_SOLD_TO_CUST_CODE=SOLDTO_CUST.SAP_CUST_CODE  )
  AND  ( DD.SALES_FACT.SAP_SHIP_TO_CUST_CODE=OD.CUST_PARTNER_FUNCN2.SAP_SHIP_TO_CUST_CODE (+) AND DD.SALES_FACT.SAP_SOLD_TO_CUST_CODE=OD.CUST_PARTNER_FUNCN2.SAP_SOLD_TO_CUST_CODE (+) AND DD.SALES_FACT.SAP_SALES_DTL_DISTBN_CHNL_CODE=OD.CUST_PARTNER_FUNCN2.SAP_DISTBN_CHNL_CODE (+) AND DD.SALES_FACT.SAP_SALES_DTL_DIVISION_CODE=OD.CUST_PARTNER_FUNCN2.SAP_DIVISION_CODE (+) AND DD.SALES_FACT.SAP_SALES_DTL_SALES_ORG_CODE=OD.CUST_PARTNER_FUNCN2.SAP_SALES_ORG_CODE (+)  )
  AND  ( DD.SALES_FORCE_GEO_HIER.SAP_HIER_CUST_CODE (+)=OD.CUST_PARTNER_FUNCN2.SAP_HIER_CUST_CODE AND DD.SALES_FORCE_GEO_HIER.SAP_DISTBN_CHNL_CODE (+)=OD.CUST_PARTNER_FUNCN2.SAP_DISTBN_CHNL_CODE AND DD.SALES_FORCE_GEO_HIER.SAP_DIVISION_CODE (+)=OD.CUST_PARTNER_FUNCN2.SAP_DIVISION_CODE AND DD.SALES_FORCE_GEO_HIER.SAP_SALES_ORG_CODE (+)=OD.CUST_PARTNER_FUNCN2.SAP_SALES_ORG_CODE  )
  AND  ( DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE  =  '131'
    AND  DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE  =  '11'
    AND  DD.DIVISION_DIM.SAP_DIVISION_CODE  =  '51'
    AND  MM.MARS_DATE.YYYYMMDD_DATE  =  20050210 )
  AND DD.SALES_FACT.SAP_PLANT_CODE = T1.SAP_PLANT_CODE
  AND DD.SALES_FACT.CRPC_PRICE_BAND IS NOT NULL 
  AND DD.SALES_FACT.CRPC_PRICE_BAND IN ('A','B')
GROUP BY
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_4, Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_4, Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_4) || '] - No Name Defined' ), DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_4), 
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_5, Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_5, Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_5) || '] - No Name Defined' ), DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_5), 
  Decode(DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_6, Null, Decode(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_6, Null, Null, '[' || to_char(DD.SALES_FORCE_GEO_HIER.SAP_CUST_CODE_LEVEL_6) || '] - No Name Defined' ), DD.SALES_FORCE_GEO_HIER.CUST_NAME_JA_LEVEL_6), 
  SOLDTO_CUST.SAP_CUST_CODE, 
  SOLDTO_CUST.CUST_NAME_JA, 
  DD.CUST_DIM.SAP_CUST_CODE, 
  DD.CUST_DIM.CUST_NAME_JA, 
  Decode(Upper(DD.MATERIAL_DIM.BRAND_FLAG_DESC), 'NOT APPLICABLE', ' ', DD.MATERIAL_DIM.BRAND_FLAG_DESC), 
  Decode(Upper(DD.MATERIAL_DIM.SUPPLY_SGMNT_DESC), 'NOT APPLICABLE', ' ', DD.MATERIAL_DIM.SUPPLY_SGMNT_DESC), 
  DD.MATERIAL_DIM.SAP_MATERIAL_CODE, 
  DD.MATERIAL_DIM.MATERIAL_DESC_JA, 
  MM.MARS_DATE.YEAR_NUM, 
  MM.MARS_DATE.MONTH_NUM, 
  MM.MARS_DATE.MONTH_DAY_NUM,
  T1.SAP_PLANT_CODE,
  T1.PLANT_DESC,
  DD.SALES_FACT.CRPC_PRICE_BAND
HAVING
  sum(DD.SALES_FACT.SALES_DTL_PRICE_VALUE_12)  !=  0;
