/******************************************************************************/
/* View Definition                                                            */
/******************************************************************************/
/**
 Object : logi_rpt_pre_001_chokuso
 Owner  : bo_user

 DESCRIPTION
 -----------
 Data Warehouse - View

 YYYY/MM   Author         Description
 -------   ------         -----------
 2005/07   Steve Gregan   Created

*******************************************************************************/

/*-*/
/* View creation
/*-*/
create or replace force view bo_user.logi_rpt_pre_001_chokuso
   (SAP_SALES_ORG_CODE, SAP_DIVISION_CODE, SAP_DISTBN_CHNL_CODE, SAP_SOLD_TO_CUST_CODE, SOLD_TO_CUST_NAME_JA, 
 SAP_SHIP_TO_CUST_CODE, SHIP_TO_CUST_NAME_JA, SHIP_TO_HIER_NAME_JA_L1, SHIP_TO_HIER_NAME_JA_L2, SHIP_TO_HIER_NAME_JA_L3, 
 SHIP_TO_HIER_NAME_JA_L4, GSV, BPS, BILLED_QTY_BASE_UOM)
AS 
SELECT
  DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE,
  DD.DIVISION_DIM.SAP_DIVISION_CODE,
  DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE,
  SOLDTO_CUST.SAP_CUST_CODE   AS SAP_SOLD_TO_CUST_CODE,
  SOLDTO_CUST.CUST_NAME_JA    AS SOLD_TO_CUST_NAME_JA,
  DD.CUST_DIM.SAP_CUST_CODE   AS SAP_SHIP_TO_CUST_CODE,
  DD.CUST_DIM.CUST_NAME_JA    AS SHIP_TO_CUST_NAME_JA,
--  DD.SALES_MONTH_01_FACT.BILLING_YYYYMM,
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_1, Null, 
    Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_1, Null, Null,
    '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_1) || '] - No Name Defined' ), 
    DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_1) AS SHIP_TO_HIER_NAME_JA_L1,
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2, Null, 
    Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2, Null, Null, 
    '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2) || '] - No Name Defined' ), 
    DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2) AS SHIP_TO_HIER_NAME_JA_L2,
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_3, Null, 
    Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_3, Null, Null, 
    '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_3) || '] - No Name Defined' ), 
    DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_3) AS SHIP_TO_HIER_NAME_JA_L3,
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_4, Null, 
    Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_4, Null, Null, 
    '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_4) || '] - No Name Defined' ), 
    DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_4) AS SHIP_TO_HIER_NAME_JA_L4,
  sum(DD.SALES_MONTH_01_FACT.SALES_DTL_PRICE_VALUE_13) AS GSV,
  sum(DD.SALES_MONTH_01_FACT.SALES_DTL_PRICE_VALUE_2)  AS BPS,
  sum(DD.SALES_MONTH_01_FACT.BASE_UOM_BILLED_QTY)      AS BILLED_QTY_BASE_UOM
FROM
  DD.SALES_ORG_DIM,
  DD.DIVISION_DIM,
  DD.DISTBN_CHNL_DIM,
  DD.CUST_DIM  SOLDTO_CUST,
  DD.CUST_DIM,
  DD.SALES_MONTH_01_FACT,
  DD.SHIP_TO_HIER
WHERE
  ( DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE=DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_DISTBN_CHNL_CODE  )
  AND  ( DD.DIVISION_DIM.SAP_DIVISION_CODE=DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_DIVISION_CODE  )
  AND  ( DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE=DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_SALES_ORG_CODE  )
  AND  ( DD.CUST_DIM.SAP_CUST_CODE=DD.SALES_MONTH_01_FACT.SAP_SHIP_TO_CUST_CODE  )
  AND  ( SOLDTO_CUST.SAP_CUST_CODE=DD.SALES_MONTH_01_FACT.SAP_SOLD_TO_CUST_CODE  )
  AND  ( DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_DISTBN_CHNL_CODE=DD.SHIP_TO_HIER.SAP_DISTBN_CHNL_CODE (+) AND DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_SALES_ORG_CODE = DD.SHIP_TO_HIER.SAP_SALES_ORG_CODE (+) AND DD.SALES_MONTH_01_FACT.SAP_SALES_DTL_DIVISION_CODE = DD.SHIP_TO_HIER.SAP_DIVISION_CODE (+) AND DD.SALES_MONTH_01_FACT.SAP_SHIP_TO_CUST_CODE=DD.SHIP_TO_HIER.SAP_HIER_CUST_CODE (+)  )
  AND  (
  DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE  =  '131'
  AND  DD.DIVISION_DIM.SAP_DIVISION_CODE  =  '51'
  AND  DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE  IN  ('10', '11')
  AND  DD.SALES_MONTH_01_FACT.BILLING_YYYYMM BETWEEN 200401 AND 200412
-- íºëóï™Ç∆ÇµÇƒë®Ç¶ÇÈÇ◊Ç´Ç‡ÇÃ
-- 15932 : ÇrÇmÇeíºëó
-- 15934 : ÇrÇmÇeÇQéüìX
-- 16111 : ÇoÇfÅ@íºëó
-- 16124 : ÇoÇfÅ@ÇQéüìX
  AND  DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2 IN (15932,15934,16111,16124)
--  AND  DD.SALES_MONTH_01_FACT.BILLING_YYYYMM BETWEEN 200401 AND 200412
--  AND  DD.SALES_MONTH_01_FACT.BILLING_YYYYMM  =  to_number( to_char( sysdate - 1, 'YYYYMM'), '000000')
--  AND  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2, Null, 
--         Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2, Null, Null, 
--         '[' || to_char(DD.SHIP_TO_HIERSAP_.CUST_CODE_LEVEL_2) || '] - No Name Defined' ), 
--         DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2)  IN  ('ÇoÇfÅ@íºëó', 'ÇrÇmÇeíºëó')
  )
GROUP BY
  DD.SALES_ORG_DIM.SAP_SALES_ORG_CODE, 
  DD.DIVISION_DIM.SAP_DIVISION_CODE, 
  DD.DISTBN_CHNL_DIM.SAP_DISTBN_CHNL_CODE, 
  SOLDTO_CUST.SAP_CUST_CODE, 
  SOLDTO_CUST.CUST_NAME_JA, 
  DD.CUST_DIM.SAP_CUST_CODE, 
  DD.CUST_DIM.CUST_NAME_JA, 
--  DD.SALES_MONTH_01_FACT.BILLING_YYYYMM, 
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_1, Null, Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_1, Null, Null, '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_1) || '] - No Name Defined' ), DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_1), 
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2, Null, Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2, Null, Null, '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_2) || '] - No Name Defined' ), DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_2), 
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_3, Null, Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_3, Null, Null, '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_3) || '] - No Name Defined' ), DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_3), 
  Decode(DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_4, Null, Decode(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_4, Null, Null, '[' || to_char(DD.SHIP_TO_HIER.SAP_CUST_CODE_LEVEL_4) || '] - No Name Defined' ), DD.SHIP_TO_HIER.CUST_NAME_JA_LEVEL_4);
