DROP MATERIALIZED VIEW MATERIAL_DIM;

CREATE MATERIALIZED VIEW MATERIAL_DIM 
TABLESPACE DD_DATA
NOCACHE
LOGGING
NOPARALLEL
USING INDEX
            TABLESPACE DD_DATA
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT * FROM MATERIAL_DIM@AP0093P.WORLD;

CREATE UNIQUE INDEX MATERIAL_DIM_PK ON MATERIAL_DIM
(SAP_MATERIAL_CODE)
LOGGING
TABLESPACE DD_DATA
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM MATERIAL_DIM FOR MATERIAL_DIM;

GRANT SELECT ON  MATERIAL_DIM TO DW_APP WITH GRANT OPTION;





