/******************************************************************************/
/* View Definition                                                            */
/******************************************************************************/
/**
 Object : care_chain_list_view
 Owner  : ftr_app

 DESCRIPTION
 -----------
 Data Warehouse - View

 YYYY/MM   Author         Description
 -------   ------         -----------
 2004/11   Steve Gregan   Created

*******************************************************************************/

/*-*/
/* View creation
/*-*/
create or replace force view ftr_app.care_chain_list_view
   (SAP_MATERIAL_CODE_TDU,
    EAN_UPC_TDU,
    MATERIAL_DESC_TDU,
    SAP_MATERIAL_CODE_MCU,
    EAN_UPC_MCU, 
    MATERIAL_DESC_MCU,
    QTY_TDU_MCU,
    SAP_MATERIAL_CODE_RSU,
    EAN_UPC_RSU,
    CARE_EAN_UPC_RSU, 
    MATERIAL_DESC_RSU,
    QTY_TDU_RSU,
    SAP_BUS_SGMNT_CODE,
    CARE_BUS_SGMNT_CODE,
    BUS_SGMNT_DESC, 
    BUS_SGMNT_ABBRD_DESC,
    SAP_MKT_SGMNT_CODE,
    CARE_MKT_SGMNT_CODE,
    MKT_SGMNT_DESC,
    MKT_SGMNT_ABBRD_DESC, 
    SAP_PRDCT_CTGRY_CODE,
    CARE_PRDCT_CTGRY_CODE,
    PRDCT_CTGRY_DESC,
    PRDCT_CTGRY_ABBRD_DESC,
    SAP_BRAND_CODE, 
    CARE_BRAND_CODE,
    BRAND_DESC,
    BRAND_ABBRD_DESC,
    SAP_PACK_SIZE_CODE,
    CARE_PACK_SIZE_CODE, 
    PACK_SIZE_DESC,
    PACK_SIZE_ABBRD_DESC,
    SAP_VRTY_CODE,
    CARE_VRTY_CODE,
    VRTY_DESC, 
    VRTY_ABBRD_DESC,
    VALID_FROM_DATE) AS 
   SELECT TDU_DIM.SAP_MATERIAL_CODE AS SAP_MATERIAL_CODE_TDU,
          TDU_DIM.EAN_UPC AS EAN_UPC_TDU,
          TDU_DIM.MATERIAL_DESC_EN AS MATERIAL_DESC_TDU,
          MCU_DIM.SAP_MATERIAL_CODE AS SAP_MATERIAL_CODE_MCU,
          MCU_DIM.EAN_UPC AS EAN_UPC_MCU,
          MCU_DIM.MATERIAL_DESC_EN AS MATERIAL_DESC_MCU,
          ATMP.TM_QTY AS QTY_TDU_MCU,
          RSU_DIM.SAP_MATERIAL_CODE AS SAP_MATERIAL_CODE_RSU,
          RSU_DIM.EAN_UPC AS EAN_UPC_RSU,
          CASE WHEN LENGTH(RSU_DIM.EAN_UPC) > 8 THEN 'IT' || SUBSTRB(RSU_DIM.EAN_UPC, -8, 8)
               ELSE CASE WHEN LENGTH(RSU_DIM.EAN_UPC) = 8 THEN 'IT' || RSU_DIM.EAN_UPC
                         ELSE  'IT' || LPAD(RSU_DIM.EAN_UPC, 8, '0') END
               END CARE_EAN_UPC_RSU,
          RSU_DIM.MATERIAL_DESC_EN AS MATERIAL_DESC_RSU,
          ATMP.TR_QTY AS QTY_TDU_RSU,
          TDU_DIM.SAP_BUS_SGMNT_CODE AS SAP_BUS_SGMNT_CODE,
          'BS' || TDU_DIM.SAP_BUS_SGMNT_CODE AS CARE_BUS_SGMNT_CODE,
          TDU_DIM.BUS_SGMNT_DESC AS BUS_SGMNT_DESC,
          TDU_DIM.BUS_SGMNT_ABBRD_DESC AS BUS_SGMNT_ABBRD_DESC,
          TDU_DIM.SAP_MKT_SGMNT_CODE AS SAP_MKT_SGMNT_CODE,
          'MS' || TDU_DIM.SAP_MKT_SGMNT_CODE AS CARE_MKT_SGMNT_CODE,
          TDU_DIM.MKT_SGMNT_DESC AS MKT_SGMNT_DESC,
          TDU_DIM.MKT_SGMNT_ABBRD_DESC AS MKT_SGMNT_ABBRD_DESC,
          SUBSTRB(NVL(TDU_DIM.SAP_PRDCT_CTGRY_CODE, '00') || NVL(TDU_DIM.SAP_SUPPLY_SGMNT_CODE, '000'), 1, 8) AS SAP_PRDCT_CTGRY_CODE,
          'PC' || SUBSTRB(NVL(TDU_DIM.SAP_PRDCT_CTGRY_CODE, '00') || NVL(TDU_DIM.SAP_SUPPLY_SGMNT_CODE, '000'), 1, 8) AS CARE_PRDCT_CTGRY_CODE,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.PRDCT_CTGRY_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.SUPPLY_SGMNT_DESC), 'Not Applicable', ''))), 1, 74), 'Not Applicable') AS PRDCT_CTGRY_DESC,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.PRDCT_CTGRY_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.SUPPLY_SGMNT_ABBRD_DESC), 'NA', ''))), 1, 40), 'NA') AS PRDCT_CTGRY_ABBRD_DESC,
          SUBSTRB(NVL(TDU_DIM.SAP_BRAND_FLAG_CODE, '000') || NVL(TDU_DIM.SAP_BRAND_SUB_FLAG_CODE, '000'), 1, 8) AS SAP_BRAND_CODE,
          'BR' || SUBSTRB(NVL(TDU_DIM.SAP_BRAND_FLAG_CODE, '000') || NVL(TDU_DIM.SAP_BRAND_SUB_FLAG_CODE, '000'), 1, 8) AS CARE_BRAND_CODE,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.BRAND_FLAG_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.BRAND_SUB_FLAG_DESC), 'Not Applicable', ''))), 1, 74), 'Not Applicable') AS BRAND_DESC,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.BRAND_FLAG_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.BRAND_SUB_FLAG_ABBRD_DESC), 'NA', ''))), 1, 40), 'NA') AS BRAND_ABBRD_DESC,
          CASE WHEN TDU_DIM.SAP_BUS_SGMNT_CODE = '05' THEN SUBSTRB(NVL(TDU_DIM.SAP_CNSMR_PACK_FRMT_CODE, '00') || NVL(TDU_DIM.SAP_PRDCT_PACK_SIZE_CODE, '000') || 'P' || NVL(TDU_DIM.SAP_MULTI_PACK_QTY_CODE, '00'), 1, 8)
               ELSE SUBSTRB(NVL(TDU_DIM.SAP_CNSMR_PACK_FRMT_CODE, '00') || NVL(TDU_DIM.SAP_PRDCT_PACK_SIZE_CODE, '000') || NVL(TDU_DIM.SAP_PRDCT_TYPE_CODE, '000'), 1, 8) END SAP_PACK_SIZE_CODE,
          'PS' || CASE WHEN TDU_DIM.SAP_BUS_SGMNT_CODE = '05' THEN SUBSTRB(NVL(TDU_DIM.SAP_CNSMR_PACK_FRMT_CODE, '00') || NVL(TDU_DIM.SAP_PRDCT_PACK_SIZE_CODE, '000') || 'P' || NVL(TDU_DIM.SAP_MULTI_PACK_QTY_CODE, '00'), 1, 8)
                  ELSE SUBSTRB(NVL(TDU_DIM.SAP_CNSMR_PACK_FRMT_CODE, '00') || NVL(TDU_DIM.SAP_PRDCT_PACK_SIZE_CODE, '000') || NVL(TDU_DIM.SAP_PRDCT_TYPE_CODE, '000'), 1, 8) END CARE_PACK_SIZE_CODE,
          NVL(CASE WHEN TDU_DIM.SAP_BUS_SGMNT_CODE = '05' THEN SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.CNSMR_PACK_FRMT_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_PACK_SIZE_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.MULTI_PACK_QTY_DESC), 'Not Applicable', ''))), 1, 74)
                   ELSE SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.CNSMR_PACK_FRMT_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_PACK_SIZE_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_TYPE_DESC), 'Not Applicable', ''))), 1, 74) END , 'Not Applicable') AS PACK_SIZE_DESC,
          NVL(CASE WHEN TDU_DIM.SAP_BUS_SGMNT_CODE = '05' THEN SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.CNSMR_PACK_FRMT_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_PACK_SIZE_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.MULTI_PACK_QTY_ABBRD_DESC), 'NA', ''))), 1, 40)
                   ELSE SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.CNSMR_PACK_FRMT_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_PACK_SIZE_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.PRDCT_TYPE_ABBRD_DESC), 'NA', ''))), 1, 40) END , 'NA') AS PACK_SIZE_ABBRD_DESC,
          SUBSTRB(NVL(TDU_DIM.SAP_FUNCL_VRTY_CODE, '000') || NVL(TDU_DIM.SAP_INGRED_VRTY_CODE, '0000'), 1, 8) AS SAP_VRTY_CODE,
          'VR' || SUBSTRB(NVL(TDU_DIM.SAP_FUNCL_VRTY_CODE, '000') || NVL(TDU_DIM.SAP_INGRED_VRTY_CODE, '0000'), 1, 8) AS CARE_VRTY_CODE,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.FUNCL_VRTY_DESC), 'Not Applicable', '') || ' ' || REPLACE(RTRIM(TDU_DIM.INGRED_VRTY_DESC), 'Not Applicable', ''))), 1, 74), 'Not Applicable') AS VRTY_DESC,
          NVL(SUBSTRB(RTRIM(LTRIM(REPLACE(RTRIM(TDU_DIM.FUNCL_VRTY_ABBRD_DESC), 'NA', '') || ' ' || REPLACE(RTRIM(TDU_DIM.INGRED_VRTY_ABBRD_DESC), 'NA', ''))), 1, 40), 'NA') AS VRTY_ABBRD_DESC,
          TO_NUMBER(TO_CHAR(ATMP.VALID_FROM_DATE, 'YYYYMMDD')) AS VALID_FROM_DATE
     FROM DD.MATERIAL_DIM TDU_DIM,
          DD.MATERIAL_DIM MCU_DIM,
          DD.MATERIAL_DIM RSU_DIM,
          (SELECT TDU_SAP_CODE,
                  MCU_SAP_CODE,
                  CASE WHEN TM_QTY >= 1000 THEN TM_QTY /1000
                       ELSE TM_QTY
                        END TM_QTY,
                  RSU_SAP_CODE,
                  CASE WHEN TR_QTY >= 1000 THEN TR_QTY / 1000
                       ELSE TR_QTY
                        END TR_QTY,
                  VALID_FROM_DATE
             FROM FTR_APP.CARE_CHAIN_CORE_VIEW
            UNION
           SELECT V1.TDU_SAP_CODE,
                  NULL AS MCU_SAP_CODE,
                  TO_NUMBER(NULL) AS TM_QTY,
                  V1.TDU_SAP_CODE AS RSU_SAP_CODE,
                  TO_NUMBER(1) AS TR_QTY,
                  ODM.MATERIAL_LUPDT AS VALID_FROM_DATE
             FROM (SELECT DMD.SAP_MATERIAL_CODE AS TDU_SAP_CODE,
                          DMD.EAN_UPC AS TDU_EAN_UPC
                     FROM DD.MATERIAL_DIM DMD
                    WHERE DMD.MATERIAL_TYPE_FLAG_TDU = 'Y' AND
                          DMD.MATERIAL_TYPE_FLAG_RSU = 'Y' AND
                          DMD.MATERIAL_TYPE_FLAG_REP = 'N' AND
                          DMD.SAP_REP_ITEM_CODE IS NOT NULL AND
                          DMD.MATERIAL_DESC_EN IS NOT NULL) V1,
                  OD.MATERIAL ODM
            WHERE ODM.SAP_MATERIAL_CODE = V1.TDU_SAP_CODE) ATMP
    WHERE TDU_DIM.SAP_MATERIAL_CODE = ATMP.TDU_SAP_CODE AND
          MCU_DIM.SAP_MATERIAL_CODE(+) = ATMP.MCU_SAP_CODE AND
          RSU_DIM.SAP_MATERIAL_CODE = ATMP.RSU_SAP_CODE
   WITH READ ONLY;

/*-*/
/* Authority
/*-*/
grant select on ftr_app.care_chain_list_view to ftr_user;

/*-*/
/* Synonym
/*-*/
create or replace public synonym care_chain_list_view for ftr_app.care_chain_list_view;