<html>
<script language="javascript">
<!--
   function setActions() {
      parent.setActions('&nbsp;');
   }
// -->
</script>
<head>
   <meta http-equiv="content-type" content="text/html;charset=Shift-JIS">
   <link rel="stylesheet" type="text/css" href="mfjpln_style.css">
</head>
<body class="clsBody02" scroll="auto" onLoad="setActions();">                   
   <table align=center valign=center border=0 cellpadding=0 cellspacing=0 cols=1 width=100%>
      <tr>
         <td class="clsHome" align=center nowrap><nobr>SYSTEM ERROR</nobr></td>
      </tr>
      <tr>
         <td class="clsLabelBB" align=center>&nbsp;</td>
      </tr>
      <tr>
         <td class="clsLabelBB" align=center>&nbsp;<%=strReturn%>&nbsp;</td>
      </tr>
   </table>
</body>
</html>