CREATE TABLE DDS.EFEX_DISTBN_XACTN_DIM
(
   DISTBN_XACTN_CODE NUMBER(10,0) NOT NULL ENABLE,
   COMPANY_CODE      VARCHAR2(6 CHAR) NOT NULL ENABLE,
   DISTBN_DATE DATE NOT NULL ENABLE,
   DISTBN_YYYYPPW           NUMBER(7,0) NOT NULL ENABLE,
   DISTBN_YYYYPP            NUMBER(6,0) NOT NULL ENABLE,
   DISTBN_CODE              NUMBER(10,0) NOT NULL ENABLE,
   CUST_DTL_CODE            NUMBER(10,0) NOT NULL ENABLE,
   EFEX_CUST_ID             NUMBER(10,0) NOT NULL ENABLE,
   SALES_TERR_CODE          NUMBER(10,0) NOT NULL ENABLE,
   EFEX_SALES_TERR_ID       NUMBER(10,0) NOT NULL ENABLE,
   EFEX_SGMNT_ID            NUMBER(10,0) NOT NULL ENABLE,
   EFEX_BUS_UNIT_ID         NUMBER(10,0) NOT NULL ENABLE,
   EFEX_MATL_ID             NUMBER(10,0) NOT NULL ENABLE,
   EFEX_MATL_SUBGRP_ID      NUMBER(10,0),
   EFEX_MATL_GRP_ID         NUMBER(10,0),
   EFEX_ASSOC_ID            NUMBER(10,0) NOT NULL ENABLE,
   EFEX_RANGE_ID            NUMBER(10,0) NOT NULL ENABLE,
   RQD_FLG_CODE             NUMBER(2,0) NOT NULL ENABLE,
   RANGED_FLG_CODE          NUMBER(2,0) NOT NULL ENABLE,
   OUTOFDATE_STOCK_FLG_CODE NUMBER(2,0),
   GAP_FLG_CODE             NUMBER(2,0) NOT NULL ENABLE,
   FACING_QTY               NUMBER(4,0),
   DISPLAY_QTY              NUMBER(4,0),
   INV_QTY                  NUMBER(4,0),
   MATL_PRICE               NUMBER(10,2),
   GAP                      NUMBER(1,0) NOT NULL ENABLE,
   GAP_NEW                  NUMBER(1,0) NOT NULL ENABLE,
   GAP_CLOSED               NUMBER(1,0) NOT NULL ENABLE,
   RQD                      NUMBER(1,0) NOT NULL ENABLE,
   RANGED                   NUMBER(1,0) NOT NULL ENABLE,
   OUTOFSTOCK               NUMBER(1,0),
   EFF_START_DATE DATE NOT NULL ENABLE,
   EFF_END_DATE DATE NOT NULL ENABLE,
   LAST_REC_FLG VARCHAR2(1 CHAR) NOT NULL ENABLE,
   STATUS       VARCHAR2(1 CHAR) NOT NULL ENABLE,
   PROMO_PRICE  VARCHAR2(50 CHAR),
   CONSTRAINT EFEX_DISTBN_XACTN_DIM_PK PRIMARY KEY (DISTBN_XACTN_CODE)
);

COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISTBN_XACTN_CODE IS 'EFEX Distribution Transaction Unique Sequence Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.COMPANY_CODE IS 'Company Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISTBN_DATE IS 'Distribution Date';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISTBN_YYYYPPW IS 'Distribution Mars Week';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISTBN_YYYYPP IS 'Distribution Mars Period';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISTBN_CODE IS 'Distribution Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.CUST_DTL_CODE IS 'Customer Detail Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_CUST_ID IS 'EFEX Customer ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.SALES_TERR_CODE IS 'Sales Territory Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_SALES_TERR_ID IS 'EFEX Sales Territory ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_SGMNT_ID IS 'EFEX Segment ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_BUS_UNIT_ID IS 'EFEX Business Unit ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_MATL_ID IS 'EFEX Material ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_MATL_SUBGRP_ID IS 'EFEX Material Subgroup ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_MATL_GRP_ID IS 'EFEX Material Group ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_ASSOC_ID IS 'EFEX Associate ID';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFEX_RANGE_ID IS 'Range Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.RQD_FLG_CODE IS 'Required Flag code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.RANGED_FLG_CODE IS 'Ranged Flag Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.OUTOFDATE_STOCK_FLG_CODE IS 'OutOfDateStock Flag Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.GAP_FLG_CODE IS 'Gap Flag Code';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.FACING_QTY IS 'Facing Quantity';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.DISPLAY_QTY IS 'Display Quantity';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.INV_QTY IS 'Inventory Quantity';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.MATL_PRICE IS 'Material Price';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.GAP IS 'Gap';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.GAP_NEW IS 'Gap New';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.GAP_CLOSED IS 'Gap Closed';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.RQD IS 'Required';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.RANGED IS 'Ranged';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.OUTOFSTOCK IS 'OutOfStock';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFF_START_DATE IS 'EFF Start Date';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.EFF_END_DATE IS 'EFF End Date';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.LAST_REC_FLG IS 'Last Recorded Flag';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.STATUS IS 'Record Status';
COMMENT ON COLUMN DDS.EFEX_DISTBN_XACTN_DIM.PROMO_PRICE IS 'Promo Price';
COMMENT ON TABLE DDS.EFEX_DISTBN_XACTN_DIM IS 'EFEX Distribution Transaction Dimension';

CREATE UNIQUE INDEX DDS.EFEX_DISTBN_XACTN_DIM_PK ON DDS.EFEX_DISTBN_XACTN_DIM
(
   DISTBN_XACTN_CODE
);

CREATE INDEX DDS.EFEX_DISTBN_XACTN_DIM_I2 ON DDS.EFEX_DISTBN_XACTN_DIM
(
   CUST_DTL_CODE,
   EFEX_MATL_ID,
   DISTBN_YYYYPPW
);

CREATE INDEX DDS.EFEX_DISTBN_XACTN_DIM_I4 ON DDS.EFEX_DISTBN_XACTN_DIM
(
   DISTBN_YYYYPPW,
   STATUS,
   LAST_REC_FLG
);

CREATE INDEX DDS.EFEX_DISTBN_XACTN_DIM_I3 ON DDS.EFEX_DISTBN_XACTN_DIM
(
   EFF_END_DATE,
   STATUS,
   LAST_REC_FLG,
   DISTBN_XACTN_CODE
);

CREATE INDEX DDS.EFEX_DISTBN_XACTN_DIM_I6 ON DDS.EFEX_DISTBN_XACTN_DIM
(
   EFEX_MATL_ID,
   EFF_END_DATE,
   EFEX_SGMNT_ID,
   LAST_REC_FLG,
   STATUS
);


CREATE INDEX DDS.EFEX_DISTBN_XACTN_DIM_I1 ON DDS.EFEX_DISTBN_XACTN_DIM
(
   EFEX_CUST_ID,
   EFEX_MATL_ID,
   DISTBN_YYYYPPW
);

