CREATE TABLE DDS.EFEX_CUST_DTL_DIM
(
   CUST_DTL_CODE      NUMBER(10,0) NOT NULL ENABLE,
   EFEX_CUST_ID       NUMBER(10,0) NOT NULL ENABLE,
   CUST_CODE          VARCHAR2(10 CHAR) NOT NULL ENABLE,
   ADDR_1             VARCHAR2(100 CHAR),
   ADDR_2             VARCHAR2(100 CHAR),
   POSTAL_ADDR        VARCHAR2(50 CHAR),
   PHONE              VARCHAR2(50 CHAR),
   VENDOR_CODE        VARCHAR2(50 CHAR),
   MERCH_CODE         VARCHAR2(50 CHAR),
   MERCH_NAME         VARCHAR2(50 CHAR),
   PAYEE_NAME         VARCHAR2(50 CHAR),
   ABN                VARCHAR2(50 CHAR),
   MEALS_DAY          NUMBER(4,0),
   LEAD_TIME          NUMBER(4,0),
   GRADE              VARCHAR2(50 CHAR),
   EFEX_BANNER_ID     NUMBER(10,0),
   EFEX_CUST_TYPE_ID  NUMBER(10,0),
   EFEX_SALES_TERR_ID NUMBER(10,0),
   SALES_TERR_CODE    NUMBER(10,0),
   EFEX_RANGE_ID      NUMBER(10,0),
   WEEK_VISIT_FREQ    NUMBER(6,2) NOT NULL ENABLE,
   PRD_VISIT_FREQ     NUMBER(6,2) NOT NULL ENABLE,
   YEAR_VISIT_FREQ    NUMBER(6,2) NOT NULL ENABLE,
   VISIT_FREQ         NUMBER(4,0) NOT NULL ENABLE,
   LAST_CALL_DATE DATE,
   LAST_ORDER_DATE DATE,
   LAST_ORDER_ID  NUMBER(10,0),
   DISC_PCT       NUMBER(10,2),
   CORPORATE_FLG  VARCHAR2(1 CHAR) NOT NULL ENABLE,
   DISTBR_FLG     VARCHAR2(1 CHAR) NOT NULL ENABLE,
   EFEX_DISTBR_ID NUMBER(10,0),
   DISTBR_CODE    NUMBER(10,0),
   ACTIVE_FLG     VARCHAR2(1 CHAR) NOT NULL ENABLE,
   EFF_START_DATE DATE NOT NULL ENABLE,
   EFF_END_DATE DATE NOT NULL ENABLE,
   LAST_REC_FLG VARCHAR2(1 CHAR) NOT NULL ENABLE,
   STATUS       VARCHAR2(1 CHAR) NOT NULL ENABLE,
   PERIOD       VARCHAR2(100 CHAR),
   CONSTRAINT EFEX_CUST_DTL_DIM_PK PRIMARY KEY (CUST_DTL_CODE) 
);

COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.CUST_DTL_CODE IS 'Customer Detail Unique Sequence ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_CUST_ID IS 'EFEX Customer Unique Sequence ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.CUST_CODE IS 'Customer Code references EFEX_CUST_DIM';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.VENDOR_CODE IS 'Vendor Unique Sequence ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.MERCH_CODE IS 'Merchandiser Unique Sequence ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.MERCH_NAME IS 'Merchandiser Name';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.PAYEE_NAME IS 'Payee Name';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.ABN IS 'ABN or VAT Registration Code';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.MEALS_DAY IS 'Meals per Day';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.LEAD_TIME IS 'Lead Time';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.GRADE IS 'Grade';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_BANNER_ID IS 'EFEX Banner ID references EFEX_BANNER_DIM';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_CUST_TYPE_ID IS 'EFEX Customer Type ID references EFEX_CHNL_DIM';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_SALES_TERR_ID IS 'EFEX Sales Territory ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.SALES_TERR_CODE IS 'EFEX Sales Territory Code references EFEX_SALES_TERR_DIM';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_RANGE_ID IS 'Range Code references EFEX_RANGE_DIM';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.WEEK_VISIT_FREQ IS 'Week Visit Frequency';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.PRD_VISIT_FREQ IS 'Period Visit Frequency';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.YEAR_VISIT_FREQ IS 'Year Visit Frequency';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.VISIT_FREQ IS 'Number of Weeks Between Visits';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.LAST_CALL_DATE IS 'Last Call Date';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.LAST_ORDER_DATE IS 'Last Order Date';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.LAST_ORDER_ID IS 'Last Order ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.DISC_PCT IS 'Discount Percentage';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.CORPORATE_FLG IS 'Corporate Flag';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.DISTBR_FLG IS 'Distributor Flag';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFEX_DISTBR_ID IS 'EFEX Distributor ID';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.DISTBR_CODE IS 'Distributor Code';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.ACTIVE_FLG IS 'Active Flag';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFF_START_DATE IS 'Start Date for the Record';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.EFF_END_DATE IS 'End Date for the Record';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.LAST_REC_FLG IS 'Last Record Flag';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.STATUS IS 'Record Status';
COMMENT ON COLUMN DDS.EFEX_CUST_DTL_DIM.PERIOD IS 'Periods for customer visits';
COMMENT ON TABLE DDS.EFEX_CUST_DTL_DIM IS 'EFEX Customer Detail Dimension';

CREATE INDEX DDS.EFEX_CUST_DTL_DIM_I1 ON DDS.EFEX_CUST_DTL_DIM
(
   EFEX_CUST_ID,
   LAST_REC_FLG
);
   
CREATE UNIQUE INDEX DDS.EFEX_CUST_DTL_DIM_PK ON DDS.EFEX_CUST_DTL_DIM
(
   CUST_DTL_CODE
);

