CREATE TABLE DDS.EFEX_ASSMNT_QUESTN_DIM
(
   EFEX_ASSMNT_ID   NUMBER(10,0) NOT NULL ENABLE,
   ASSMNT_QUESTN    VARCHAR2(4000 CHAR) NOT NULL ENABLE,
   QUESTN_GRP       VARCHAR2(50 CHAR) NOT NULL ENABLE,
   EFEX_SGMNT_ID    NUMBER(10,0) NOT NULL ENABLE,
   EFEX_BUS_UNIT_ID NUMBER(10,0) NOT NULL ENABLE,
   EFF_START_DATE DATE NOT NULL ENABLE,
   EFF_END_DATE DATE NOT NULL ENABLE,
   DUE_DATE DATE NOT NULL ENABLE,
   STATUS     VARCHAR2(1 CHAR) NOT NULL ENABLE,
   ASSMNT_TITLE VARCHAR2(50 CHAR),
   CONSTRAINT EFEX_ASSMNT_QUESTN_DIM_PK PRIMARY KEY (EFEX_ASSMNT_ID) 
);

COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.EFEX_ASSMNT_ID IS 'Sales Territory Unique Sequence ID';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.ASSMNT_QUESTN IS 'Sales Territory Manager ID references EFEX_ASSOC_DIM';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.QUESTN_GRP IS 'Sales Territory Name';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.EFEX_SGMNT_ID IS 'EFEX Sales Area ID';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.EFEX_BUS_UNIT_ID IS 'Sales Area Name';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.EFF_START_DATE IS 'Start Date for the Record';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.EFF_END_DATE IS 'End Date for the Record';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.DUE_DATE IS 'End Date for the Record';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.STATUS IS 'Record Status';
COMMENT ON COLUMN DDS.EFEX_ASSMNT_QUESTN_DIM.ASSMNT_TITLE IS 'Assessment Title';
COMMENT ON TABLE DDS.EFEX_ASSMNT_QUESTN_DIM IS 'EFEX Assessment Question Dimension';
