CREATE TABLE ODS.EFEX_CUST
(
   EFEX_CUST_ID       NUMBER(10,0) NOT NULL ENABLE,
   CUST_CODE          VARCHAR2(50 CHAR),
   CUST_NAME          VARCHAR2(100 CHAR) NOT NULL ENABLE,
   ADDR_1             VARCHAR2(100 CHAR),
   ADDR_2             VARCHAR2(100 CHAR),
   POSTAL_ADDR        VARCHAR2(50 CHAR),
   CITY               VARCHAR2(50 CHAR),
   STATE              VARCHAR2(50 CHAR),
   POSTCODE           VARCHAR2(50 CHAR),
   PHONE              VARCHAR2(50 CHAR),
   DISTBR_FLG         VARCHAR2(1 CHAR),
   OUTLET_FLG         VARCHAR2(1 CHAR),
   ACTIVE_FLG         VARCHAR2(1 CHAR),
   SALES_TERR_ID      NUMBER(10,0),
   RANGE_ID           NUMBER(10,0),
   CUST_VISIT_FREQ_ID NUMBER(10,0),
   CUST_VISIT_FREQ    VARCHAR2(50 CHAR),
   CUST_TYPE_ID       NUMBER(10,0),
   AFFLTN_ID          NUMBER(10,0),
   DISTBR_ID          NUMBER(10,0),
   CUST_GRADE_ID      NUMBER(10,0),
   CUST_GRADE         VARCHAR2(50 CHAR),
   PAYEE_NAME         VARCHAR2(50 CHAR),
   MERCH_NAME         VARCHAR2(50 CHAR),
   MERCH_CODE         VARCHAR2(50 CHAR),
   VENDOR_CODE        VARCHAR2(50 CHAR),
   ABN                VARCHAR2(50 CHAR),
   MEALS_DAY          NUMBER(4,0),
   LEAD_TIME          NUMBER(4,0),
   DISC_PCT           NUMBER(10,2),
   CORPORATE_FLG      VARCHAR2(1 CHAR),
   EFEX_LUPDT DATE NOT NULL ENABLE,
   STATUS        VARCHAR2(1 CHAR) NOT NULL ENABLE,
   VALDTN_STATUS VARCHAR2(10 CHAR) NOT NULL ENABLE,
   CUST_LUPDP    VARCHAR2(8 CHAR) NOT NULL ENABLE,
   CUST_LUPDT DATE NOT NULL ENABLE,
   EFEX_MKT_ID        NUMBER(10,0) NOT NULL ENABLE,
   CALL_WEEK1_DAY     NUMBER(4,0),
   CALL_WEEK2_DAY     NUMBER(4,0),
   CALL_WEEK3_DAY     NUMBER(4,0),
   CALL_WEEK4_DAY     NUMBER(4,0),
   CALL_WEEK1_DAY_SEQ NUMBER(4,0),
   CALL_WEEK2_DAY_SEQ NUMBER(4,0),
   CALL_WEEK3_DAY_SEQ NUMBER(4,0),
   CALL_WEEK4_DAY_SEQ NUMBER(4,0),
   PERIOD             VARCHAR2(100 CHAR),
   CONSTRAINT EFEX_CUST_PK PRIMARY KEY (EFEX_CUST_ID)
);

COMMENT ON COLUMN ODS.EFEX_CUST.EFEX_CUST_ID IS 'EFEX Customer Sequence ID';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_CODE IS 'Customer Code';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_NAME IS 'Customer Name';
COMMENT ON COLUMN ODS.EFEX_CUST.ADDR_1 IS 'Customer Address Line 2';
COMMENT ON COLUMN ODS.EFEX_CUST.POSTAL_ADDR IS 'Customer Postal Address';
COMMENT ON COLUMN ODS.EFEX_CUST.CITY IS 'Customer City';
COMMENT ON COLUMN ODS.EFEX_CUST.STATE IS 'Customer State';
COMMENT ON COLUMN ODS.EFEX_CUST.POSTCODE IS 'Customer Postcode';
COMMENT ON COLUMN ODS.EFEX_CUST.PHONE IS 'Customer Phone Number';
COMMENT ON COLUMN ODS.EFEX_CUST.DISTBR_FLG IS 'Customer Distributor Flag';
COMMENT ON COLUMN ODS.EFEX_CUST.OUTLET_FLG IS 'Customer Outlet Flag';
COMMENT ON COLUMN ODS.EFEX_CUST.ACTIVE_FLG IS 'Customer Active Flag';
COMMENT ON COLUMN ODS.EFEX_CUST.SALES_TERR_ID IS 'Customer Sales Territory Unique ID';
COMMENT ON COLUMN ODS.EFEX_CUST.RANGE_ID IS 'Range Unique ID';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_VISIT_FREQ_ID IS 'Customer Visit Frequency ID';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_VISIT_FREQ IS 'Number of Weeks Between Calls';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_TYPE_ID IS 'Customer Type unique sequence ID';
COMMENT ON COLUMN ODS.EFEX_CUST.AFFLTN_ID IS 'Affiliation unique ID';
COMMENT ON COLUMN ODS.EFEX_CUST.DISTBR_ID IS 'Distributor unique ID';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_GRADE_ID IS 'Customer Grade unique ID';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_GRADE IS 'Customer Grade';
COMMENT ON COLUMN ODS.EFEX_CUST.PAYEE_NAME IS 'Customer Name';
COMMENT ON COLUMN ODS.EFEX_CUST.MERCH_NAME IS 'Payee Name';
COMMENT ON COLUMN ODS.EFEX_CUST.VENDOR_CODE IS 'Vendor Code';
COMMENT ON COLUMN ODS.EFEX_CUST.ABN IS 'ABN Number';
COMMENT ON COLUMN ODS.EFEX_CUST.MEALS_DAY IS 'Meals per Day';
COMMENT ON COLUMN ODS.EFEX_CUST.LEAD_TIME IS 'Lead Time';
COMMENT ON COLUMN ODS.EFEX_CUST.DISC_PCT IS 'Customer Discount Percent';
COMMENT ON COLUMN ODS.EFEX_CUST.CORPORATE_FLG IS 'Corporate Customer Flag';
COMMENT ON COLUMN ODS.EFEX_CUST.EFEX_LUPDT IS 'Last update date and time of the EFEX CUSTOMER table record';
COMMENT ON COLUMN ODS.EFEX_CUST.STATUS IS 'Record Status';
COMMENT ON COLUMN ODS.EFEX_CUST.VALDTN_STATUS IS 'Validation Status';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_LUPDP IS 'User who last modified record';
COMMENT ON COLUMN ODS.EFEX_CUST.CUST_LUPDT IS 'Date record was last modified';
COMMENT ON COLUMN ODS.EFEX_CUST.EFEX_MKT_ID IS 'Efex Market Unique Sequence Id';
COMMENT ON COLUMN ODS.EFEX_CUST.CALL_WEEK1_DAY IS 'Week 4 day to call on customer 0=Sunday';
COMMENT ON COLUMN ODS.EFEX_CUST.CALL_WEEK1_DAY_SEQ IS 'Week 4 day sequence to call on customer 0=Sunday';
COMMENT ON COLUMN ODS.EFEX_CUST.PERIOD IS 'Periods for customer visits';
COMMENT ON TABLE ODS.EFEX_CUST IS 'EFEX Customer';

CREATE OR REPLACE TRIGGER ODS.EFEX_CUST_UPDT
/*********************************************************************************
DESCRIPTION:
Updates efex_cust_lupdp and efex_cust_lupdt columns in efex_cust table
whenever a new record is added or updated.
REVISIONS:
Ver   Date       Author               Description
----- ---------- -------------------- ----------------------------------------
1.0   Sept 2007   John Cho           Created the Trigger.
*********************************************************************************/
   BEFORE
   INSERT OR
   UPDATE ON ODS.EFEX_CUST FOR EACH ROW BEGIN :NEW.cust_lupdt := SYSDATE;
   :NEW.cust_lupdp := USER;
END;
/
ALTER TRIGGER ODS.EFEX_CUST_UPDT ENABLE;
