ALTER TABLE BDS.BDS_REFRNC_PURCHASING_SRC_CML
 DROP PRIMARY KEY CASCADE;

DROP TABLE BDS.BDS_REFRNC_PURCHASING_SRC_CML CASCADE CONSTRAINTS;

CREATE TABLE BDS.BDS_REFRNC_PURCHASING_SRC_CML
(
  SAP_MATERIAL_CODE              VARCHAR2(18 CHAR) NOT NULL,
  PLANT_CODE                     VARCHAR2(4 CHAR) NOT NULL,
  SRC_LIST_VALID_FROM            DATE           NOT NULL,
  SRC_LIST_VALID_TO              DATE           NOT NULL,
  PURCHASING_ORGANISATION        VARCHAR2(4 CHAR) NOT NULL,
  VENDOR_CODE                    VARCHAR2(10 CHAR) NOT NULL,
  AGREEMENT_NO                   VARCHAR2(10 CHAR) NOT NULL,
  AGREEMENT_ITEM                 VARCHAR2(5 CHAR) NOT NULL,
  PLANT_PROCURED_FROM            VARCHAR2(4 CHAR) NOT NULL,
  SRC_LIST_PLANNING_USAGE        VARCHAR2(4 CHAR) NOT NULL,
  FIXED_VENDOR_INDCTR            VARCHAR2(4 CHAR) NOT NULL,
  CREATN_DATE                    DATE,
  CREATN_USER                    VARCHAR2(12 CHAR),
  FIXED_PURCHASE_AGREEMENT_ITEM  VARCHAR2(1 CHAR),
  STO_FIXED_ISSUING_PLANT        VARCHAR2(1 CHAR),
  MANUFCTR_PART_REFRNC_MATERIAL  VARCHAR2(18 CHAR),
  BLOCKED_SUPPLY_SRC_FLAG        VARCHAR2(1 CHAR),
  PURCHASING_DOCUMENT_CTGRY      VARCHAR2(1 CHAR),
  SRC_LIST_CTGRY                 VARCHAR2(1 CHAR),
  ORDER_UNIT                     VARCHAR2(3 CHAR),
  LOGICAL_SYSTEM                 VARCHAR2(10 CHAR),
  SPECIAL_STOCK_INDCTR           VARCHAR2(1 CHAR)
)
TABLESPACE BDS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BDS.BDS_REFRNC_PURCHASING_SRC_CML IS 'Business Data Store - Reference Data - Purchasing Source List Cumulative (ZDISTR - EORD)';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SAP_MATERIAL_CODE IS 'Material Number - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.PLANT_CODE IS 'Plant - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SRC_LIST_VALID_FROM IS 'Source list record valid from - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SRC_LIST_VALID_TO IS 'Source list record valid to - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.PURCHASING_ORGANISATION IS 'Purchasing Organization - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.VENDOR_CODE IS 'Account Number of the Vendor - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.AGREEMENT_NO IS 'Agreement number - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.AGREEMENT_ITEM IS 'Agreement item - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.PLANT_PROCURED_FROM IS 'Plant from which material is procured - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SRC_LIST_PLANNING_USAGE IS 'Source list usage in materials planning and control - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.FIXED_VENDOR_INDCTR IS 'Indicator: Fixed vendor - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.CREATN_DATE IS 'Date on which the record was created - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.CREATN_USER IS 'Name of Person who Created the Object - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.FIXED_PURCHASE_AGREEMENT_ITEM IS 'Fixed outline purchase agreement item - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.STO_FIXED_ISSUING_PLANT IS 'Fixed issuing plant in case of stock transport order - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.MANUFCTR_PART_REFRNC_MATERIAL IS 'Material number corresponding to manufacturer part number - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.BLOCKED_SUPPLY_SRC_FLAG IS 'Blocked source of supply - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.PURCHASING_DOCUMENT_CTGRY IS 'Purchasing document category - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SRC_LIST_CTGRY IS 'Category of source list record - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.ORDER_UNIT IS 'Order unit - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.LOGICAL_SYSTEM IS 'Logical System - LADS_REF_DAT.Z_TABNAME';

COMMENT ON COLUMN BDS.BDS_REFRNC_PURCHASING_SRC_CML.SPECIAL_STOCK_INDCTR IS 'Special Stock Indicator - LADS_REF_DAT.Z_TABNAME';



CREATE UNIQUE INDEX BDS.BDS_REFRNC_PRCHSNG_SRC_CML_PK ON BDS.BDS_REFRNC_PURCHASING_SRC_CML
(SAP_MATERIAL_CODE, PLANT_CODE, SRC_LIST_VALID_FROM, SRC_LIST_VALID_TO, PURCHASING_ORGANISATION, 
VENDOR_CODE, AGREEMENT_NO, AGREEMENT_ITEM, PLANT_PROCURED_FROM, SRC_LIST_PLANNING_USAGE, 
FIXED_VENDOR_INDCTR)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM BDS_REFRNC_PURCHASING_SRC_CML;

CREATE OR REPLACE PUBLIC SYNONYM BDS_REFRNC_PURCHASING_SRC_CML FOR BDS.BDS_REFRNC_PURCHASING_SRC_CML;


ALTER TABLE BDS.BDS_REFRNC_PURCHASING_SRC_CML ADD (
  CONSTRAINT BDS_REFRNC_PRCHSNG_SRC_CML_PK
  PRIMARY KEY
  (SAP_MATERIAL_CODE, PLANT_CODE, SRC_LIST_VALID_FROM, SRC_LIST_VALID_TO, PURCHASING_ORGANISATION, VENDOR_CODE, AGREEMENT_NO, AGREEMENT_ITEM, PLANT_PROCURED_FROM, SRC_LIST_PLANNING_USAGE, FIXED_VENDOR_INDCTR)
  USING INDEX .BDS_REFRNC_PRCHSNG_SRC_CML_PK);

GRANT DELETE, INSERT, SELECT, UPDATE ON BDS.BDS_REFRNC_PURCHASING_SRC_CML TO BDS_APP;

GRANT SELECT ON BDS.BDS_REFRNC_PURCHASING_SRC_CML TO PUBLIC WITH GRANT OPTION;
