ALTER TABLE BDS.BDS_MATERIAL_CLASSFCTN
 DROP PRIMARY KEY CASCADE;

DROP TABLE BDS.BDS_MATERIAL_CLASSFCTN CASCADE CONSTRAINTS;

CREATE TABLE BDS.BDS_MATERIAL_CLASSFCTN
(
  SAP_MATERIAL_CODE             VARCHAR2(18 CHAR) NOT NULL,
  BDS_LADS_DATE                 DATE,
  BDS_LADS_STATUS               VARCHAR2(2 CHAR),
  SAP_IDOC_NAME                 VARCHAR2(30 CHAR),
  SAP_IDOC_NUMBER               NUMBER,
  SAP_IDOC_TIMESTAMP            VARCHAR2(14 CHAR),
  SAP_BUS_SGMNT_CODE            VARCHAR2(30 CHAR),
  SAP_MRKT_SGMNT_CODE           VARCHAR2(30 CHAR),
  SAP_BRAND_FLAG_CODE           VARCHAR2(30 CHAR),
  SAP_FUNCL_VRTY_CODE           VARCHAR2(30 CHAR),
  SAP_INGRDNT_VRTY_CODE         VARCHAR2(30 CHAR),
  SAP_BRAND_SUB_FLAG_CODE       VARCHAR2(30 CHAR),
  SAP_SUPPLY_SGMNT_CODE         VARCHAR2(30 CHAR),
  SAP_TRADE_SECTOR_CODE         VARCHAR2(30 CHAR),
  SAP_OCCSN_CODE                VARCHAR2(30 CHAR),
  SAP_MRKTING_CONCPT_CODE       VARCHAR2(30 CHAR),
  SAP_MULTI_PACK_QTY_CODE       VARCHAR2(30 CHAR),
  SAP_PRDCT_CTGRY_CODE          VARCHAR2(30 CHAR),
  SAP_PACK_TYPE_CODE            VARCHAR2(30 CHAR),
  SAP_SIZE_CODE                 VARCHAR2(30 CHAR),
  SAP_SIZE_GRP_CODE             VARCHAR2(30 CHAR),
  SAP_PRDCT_TYPE_CODE           VARCHAR2(30 CHAR),
  SAP_TRAD_UNIT_CONFIG_CODE     VARCHAR2(30 CHAR),
  SAP_TRAD_UNIT_FRMT_CODE       VARCHAR2(30 CHAR),
  SAP_DSPLY_STORG_CONDTN_CODE   VARCHAR2(30 CHAR),
  SAP_ONPACK_CNSMR_VALUE_CODE   VARCHAR2(30 CHAR),
  SAP_ONPACK_CNSMR_OFFER_CODE   VARCHAR2(30 CHAR),
  SAP_ONPACK_TRADE_OFFER_CODE   VARCHAR2(30 CHAR),
  SAP_BRAND_ESSNC_CODE          VARCHAR2(30 CHAR),
  SAP_CNSMR_PACK_FRMT_CODE      VARCHAR2(30 CHAR),
  SAP_CUISINE_CODE              VARCHAR2(30 CHAR),
  SAP_FPPS_MINOR_PACK_CODE      VARCHAR2(30 CHAR),
  SAP_FIGHTING_UNIT_CODE        VARCHAR2(30 CHAR),
  SAP_CHINA_BDT_CODE            VARCHAR2(30 CHAR),
  SAP_MRKT_CTGRY_CODE           VARCHAR2(30 CHAR),
  SAP_MRKT_SUB_CTGRY_CODE       VARCHAR2(30 CHAR),
  SAP_MRKT_SUB_CTGRY_GRP_CODE   VARCHAR2(30 CHAR),
  SAP_SOP_BUS_CODE              VARCHAR2(30 CHAR),
  SAP_PRODCTN_LINE_CODE         VARCHAR2(30 CHAR),
  SAP_PLANNING_SRC_CODE         VARCHAR2(30 CHAR),
  SAP_SUB_FIGHTING_UNIT_CODE    VARCHAR2(30 CHAR),
  SAP_RAW_FAMILY_CODE           VARCHAR2(30 CHAR),
  SAP_RAW_SUB_FAMILY_CODE       VARCHAR2(30 CHAR),
  SAP_RAW_GROUP_CODE            VARCHAR2(30 CHAR),
  SAP_ANIMAL_PARTS_CODE         VARCHAR2(30 CHAR),
  SAP_PHYSICAL_CONDTN_CODE      VARCHAR2(30 CHAR),
  SAP_PACK_FAMILY_CODE          VARCHAR2(30 CHAR),
  SAP_PACK_SUB_FAMILY_CODE      VARCHAR2(30 CHAR),
  SAP_CHINA_ABC_INDCTR_CODE     VARCHAR2(30 CHAR),
  SAP_NZ_PROMOTIONAL_GRP_CODE   VARCHAR2(30 CHAR),
  SAP_NZ_SOP_BUSINESS_CODE      VARCHAR2(30 CHAR),
  SAP_NZ_MUST_WIN_CTGRY_CODE    VARCHAR2(30 CHAR),
  SAP_AU_SNK_ACTIVITY_NAME      VARCHAR2(30 CHAR),
  SAP_CHINA_FORECAST_GROUP      VARCHAR2(30 CHAR),
  SAP_HK_SUB_CTGRY_CODE         VARCHAR2(30 CHAR),
  SAP_HK_LINE_CODE              VARCHAR2(30 CHAR),
  SAP_HK_PRODUCT_SGMNT_CODE     VARCHAR2(30 CHAR),
  SAP_HK_TYPE_CODE              VARCHAR2(30 CHAR),
  SAP_STRGY_GRP_CODE            VARCHAR2(30 CHAR),
  SAP_TH_BOI_CODE               VARCHAR2(30 CHAR),
  SAP_PACK_DSPSAL_CLASS         VARCHAR2(30 CHAR),
  SAP_TH_BOI_GRP_CODE           VARCHAR2(30 CHAR),
  SAP_NZ_LAUNCH_RANKING_CODE    VARCHAR2(30 CHAR),
  SAP_NZ_SELECTIVELY_GROW_CODE  VARCHAR2(30 CHAR),
  SAP_RAW_TH_BOI_GRP_CODE       VARCHAR2(30 CHAR),
  SAP_RAW_ALLERGEN_CODE         VARCHAR2(30 CHAR)
)
TABLESPACE BDS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE BDS.BDS_MATERIAL_CLASSFCTN IS 'Business Data Store - Material Classification (CLFMAS01)';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MATERIAL_CODE IS 'SAP Material Code - LADS_CLA_HDR.OBJEK';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.BDS_LADS_DATE IS 'LADS Date - LADS_CLA_HDR.LADS_DATE';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.BDS_LADS_STATUS IS 'LADS Status - LADS_CLA_HDR.LADS_STATUS';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_IDOC_NAME IS 'IDOC Name - LADS_CLA_HDR.IDOC_NAME';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_IDOC_NUMBER IS 'IDOC Number - LADS_CLA_HDR.IDOC_NUMBER';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_IDOC_TIMESTAMP IS 'IDOC Timestamp - LADS_CLA_HDR.IDOC_TIMESTAMP';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_BUS_SGMNT_CODE IS 'SAP Business Segment - LADS_CLA_CHR.ATWRT - CLFFERT01';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MRKT_SGMNT_CODE IS 'SAP Market Segment - LADS_CLA_CHR.ATWRT - CLFFERT02';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_BRAND_FLAG_CODE IS 'SAP Brand Flag - LADS_CLA_CHR.ATWRT - CLFFERT03';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_FUNCL_VRTY_CODE IS 'SAP Functional variety - LADS_CLA_CHR.ATWRT - CLFFERT07';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_INGRDNT_VRTY_CODE IS 'SAP Ingredient Variety - LADS_CLA_CHR.ATWRT - CLFFERT06';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_BRAND_SUB_FLAG_CODE IS 'SAP Brand Sub Flag - LADS_CLA_CHR.ATWRT - CLFFERT04';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_SUPPLY_SGMNT_CODE IS 'SAP Supply Segment - LADS_CLA_CHR.ATWRT - CLFFERT05';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_TRADE_SECTOR_CODE IS 'SAP Trade Sector - LADS_CLA_CHR.ATWRT - CLFFERT08';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_OCCSN_CODE IS 'SAP Occasion - LADS_CLA_CHR.ATWRT - CLFFERT11';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MRKTING_CONCPT_CODE IS 'SAP Marketing Concept - LADS_CLA_CHR.ATWRT - CLFFERT09';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MULTI_PACK_QTY_CODE IS 'SAP Multipack Quantity - LADS_CLA_CHR.ATWRT - CLFFERT10';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PRDCT_CTGRY_CODE IS 'SAP Product Category - LADS_CLA_CHR.ATWRT - CLFFERT12';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PACK_TYPE_CODE IS 'SAP Pack Type - LADS_CLA_CHR.ATWRT - CLFFERT17';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_SIZE_CODE IS 'SAP Size - LADS_CLA_CHR.ATWRT - CLFFERT14';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_SIZE_GRP_CODE IS 'SAP Size Group - LADS_CLA_CHR.ATWRT - CLFFERT18';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PRDCT_TYPE_CODE IS 'SAP Product Type - LADS_CLA_CHR.ATWRT - CLFFERT13';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_TRAD_UNIT_CONFIG_CODE IS 'SAP Traded Unit Configuration - LADS_CLA_CHR.ATWRT - CLFFERT21';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_TRAD_UNIT_FRMT_CODE IS 'SAP Traded Unit Format - LADS_CLA_CHR.ATWRT - CLFFERT20';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_DSPLY_STORG_CONDTN_CODE IS 'SAP Display Storage Condition - LADS_CLA_CHR.ATWRT - CLFFERT19';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_ONPACK_CNSMR_VALUE_CODE IS 'SAP On-pack Consumer Value - LADS_CLA_CHR.ATWRT - CLFFERT22';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_ONPACK_CNSMR_OFFER_CODE IS 'SAP On-pack Consumer Offer - LADS_CLA_CHR.ATWRT - CLFFERT23';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_ONPACK_TRADE_OFFER_CODE IS 'SAP On-pack Trade Offer - LADS_CLA_CHR.ATWRT - CLFFERT24';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_BRAND_ESSNC_CODE IS 'SAP Brand Essence - LADS_CLA_CHR.ATWRT - CLFFERT16';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_CNSMR_PACK_FRMT_CODE IS 'SAP Consumer Pack Format - LADS_CLA_CHR.ATWRT - CLFFERT25';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_CUISINE_CODE IS 'SAP Cuisine - LADS_CLA_CHR.ATWRT - CLFFERT40';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_FPPS_MINOR_PACK_CODE IS 'SAP FPPS Minor Pack - LADS_CLA_CHR.ATWRT - CLFFERT38';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_FIGHTING_UNIT_CODE IS 'SAP Fighting Unit - LADS_CLA_CHR.ATWRT - Z_APCHAR6';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_CHINA_BDT_CODE IS 'SAP China BDT - LADS_CLA_CHR.ATWRT - Z_APCHAR7';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MRKT_CTGRY_CODE IS 'SAP Market Category - LADS_CLA_CHR.ATWRT - Z_APCHAR1';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MRKT_SUB_CTGRY_CODE IS 'SAP Market Sub Category - LADS_CLA_CHR.ATWRT - Z_APCHAR2';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_MRKT_SUB_CTGRY_GRP_CODE IS 'SAP Market Sub Category Group - LADS_CLA_CHR.ATWRT - Z_APCHAR3';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_SOP_BUS_CODE IS 'SAP S and OP Business Code - LADS_CLA_CHR.ATWRT - Z_APCHAR4';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PRODCTN_LINE_CODE IS 'SAP Production Line - LADS_CLA_CHR.ATWRT - Z_APCHAR5';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PLANNING_SRC_CODE IS 'SAP Planning Source - LADS_CLA_CHR.ATWRT - Z_APCHAR8';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_SUB_FIGHTING_UNIT_CODE IS 'SAP Sub Fighting Unit - LADS_CLA_CHR.ATWRT - Z_APCHAR9';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_RAW_FAMILY_CODE IS 'SAP Raws Family  - LADS_CLA_CHR.ATWRT - CLFROH01';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_RAW_SUB_FAMILY_CODE IS 'SAP Raws Sub Family - LADS_CLA_CHR.ATWRT - CLFROH02';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_RAW_GROUP_CODE IS 'SAP Raws Group - LADS_CLA_CHR.ATWRT - CLFROH03';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_ANIMAL_PARTS_CODE IS 'SAP Animal Parts - LADS_CLA_CHR.ATWRT - CLFROH04';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PHYSICAL_CONDTN_CODE IS 'SAP Physical Condition - LADS_CLA_CHR.ATWRT - CLFROH05';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PACK_FAMILY_CODE IS 'SAP Pack Family - LADS_CLA_CHR.ATWRT - CLFVERP01';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PACK_SUB_FAMILY_CODE IS 'SAP Packs Sub Family - LADS_CLA_CHR.ATWRT - CLFVERP02';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_CHINA_ABC_INDCTR_CODE IS 'SAP China ABC Indicator - LADS_CLA_CHR.ATWRT - Z_APCHAR10';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_NZ_PROMOTIONAL_GRP_CODE IS 'SAP NZ Promotional Group - LADS_CLA_CHR.ATWRT - Z_APCHAR11';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_NZ_SOP_BUSINESS_CODE IS 'SAP NZ SandOP Business - LADS_CLA_CHR.ATWRT - Z_APCHAR12';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_NZ_MUST_WIN_CTGRY_CODE IS 'SAP NZ Must Win Category - LADS_CLA_CHR.ATWRT - Z_APCHAR13';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_AU_SNK_ACTIVITY_NAME IS 'SAP AU SNK Activity Name - LADS_CLA_CHR.ATWRT - Z_APCHAR14';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_CHINA_FORECAST_GROUP IS 'SAP CN Forecast Group - LADS_CLA_CHR.ATWRT - Z_APCHAR15';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_HK_SUB_CTGRY_CODE IS 'SAP HK Sub Category - LADS_CLA_CHR.ATWRT - Z_APCHAR16';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_HK_LINE_CODE IS 'SAP HK Line - LADS_CLA_CHR.ATWRT - Z_APCHAR17';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_HK_PRODUCT_SGMNT_CODE IS 'SAP HK Product Segment - LADS_CLA_CHR.ATWRT - Z_APCHAR18';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_HK_TYPE_CODE IS 'SAP HK Type - LADS_CLA_CHR.ATWRT - Z_APCHAR19';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_STRGY_GRP_CODE IS 'SAP AU Strategy Group - LADS_CLA_CHR.ATWRT - Z_APCHAR20';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_TH_BOI_CODE IS 'SAP TH BOI - LADS_CLA_CHR.ATWRT - Z_APCHAR21';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_PACK_DSPSAL_CLASS IS 'SAP Pack Disposal Class - LADS_CLA_CHR.ATWRT - Z_APVERP01';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_TH_BOI_GRP_CODE IS 'SAP TH BOI Group - LADS_CLA_CHR.ATWRT - Z_APVERP02';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_NZ_LAUNCH_RANKING_CODE IS 'SAP NZ Launch Ranking Code - LADS_CLA_CHR.ATWRT - Z_APCHAR22';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_NZ_SELECTIVELY_GROW_CODE IS 'SAP NZ Selectively Grow Code - LADS_CLA_CHR.ATWRT - Z_APCHAR23';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_RAW_TH_BOI_GRP_CODE IS 'SAP TH RAW BOI Group - LADS_CLA_CHR.ATWRT - ZZAPROH';

COMMENT ON COLUMN BDS.BDS_MATERIAL_CLASSFCTN.SAP_RAW_ALLERGEN_CODE IS 'SAP RAW Allergen Code - LADS_CLA_CHR.ATWRT - CLFFERT66';



CREATE UNIQUE INDEX BDS.BDS_MATERIAL_CLASSFCTN_PK ON BDS.BDS_MATERIAL_CLASSFCTN
(SAP_MATERIAL_CODE)
LOGGING
TABLESPACE BDS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM BDS_MATERIAL_CLASSFCTN;

CREATE OR REPLACE PUBLIC SYNONYM BDS_MATERIAL_CLASSFCTN FOR BDS.BDS_MATERIAL_CLASSFCTN;


ALTER TABLE BDS.BDS_MATERIAL_CLASSFCTN ADD (
  CONSTRAINT BDS_MATERIAL_CLASSFCTN_PK
  PRIMARY KEY
  (SAP_MATERIAL_CODE)
  USING INDEX BDS.BDS_MATERIAL_CLASSFCTN_PK);

GRANT DELETE, INSERT, SELECT, UPDATE ON BDS.BDS_MATERIAL_CLASSFCTN TO BDS_APP;

grant select on bds_material_classfctn to public;