#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFileLoaderUtility.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FlatFileLoaderUtility.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 7 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - File Loader Utility</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 237), Tuple.Create("\"", 260)
, Tuple.Create(Tuple.Create("", 244), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico?v2")
, 244), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" href=\"/Content/site.minified.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var isTest = ");

            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
                 Write((ViewBag.IsTest ?? false).ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral(";\r\n    </script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/scripts/site.minified.js?v2\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/scripts/jtable/jquery.jtable.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("JavascriptImport", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            $(\"#ddlConnection\").chose" +
"n({ search_contains: true });\r\n            $(\"#ddlConnection\").change(function (" +
") {\r\n                $.ajax({\r\n                    type: \"post\",\r\n              " +
"      url: \"/Base/SetConnection\",\r\n                    data: {\r\n                " +
"        connectionId: $(this).val()\r\n                    },\r\n                   " +
" xhrFields: {\r\n                        withCredentials: true\r\n                  " +
"  },\r\n                    success: function (response) {\r\n                      " +
"  window.location.href = \"/\";\r\n                    },\r\n                    error" +
": function (xhr, ajaxOptions, thrownError) {\r\n                        alert(\"Err" +
"or communicating with server.\" + ((isTest) ? \" Exception: \" + thrownError : \"\"))" +
";\r\n                    }\r\n                });\r\n            });\r\n            if (" +
"$(\"#ddlConnection\").val() == \"\") {\r\n                $(\"#body :input\").prop(\"disa" +
"bled\", true).trigger(\"liszt:updated\");\r\n                $(\"#body\").off(\"click\");" +
"\r\n                $(\"#connectionForm\").validationEngine(\"attach\", {\r\n           " +
"         prettySelect: true,\r\n                    useSuffix: \"_chzn\",\r\n         " +
"           promptPosition: \"bottomLeft\",\r\n                    custom_error_messa" +
"ges: {\r\n                        \"#ddlConnection\": {\r\n                           " +
" \"required\": {\r\n                                message: \"<strong>Note:</strong>" +
" You must first select a database to connect to\"\r\n                            }\r" +
"\n                        }\r\n                    }\r\n                });\r\n        " +
"        $(\"#connectionForm\").validationEngine(\"validate\");\r\n            }\r\n     " +
"       $(\'.menu\').dropit();\r\n        });\r\n    </script>\r\n</head>\r\n<body>\r\n    <h" +
"eader>\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"logo\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2748), Tuple.Create("\"", 2783)
            
            #line 65 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2755), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 2755), false)
);

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" id=\"connectionForm\"");

WriteLiteral(" action=\"/\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.DropDownList("ddlConnection", (List<SelectListItem>)ViewBag.Connections, new { id = "ddlConnection", @class = "validate[required]" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                        <li ");

            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuUpload ?? false)
                            { 

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("class=\"current\" \r\n");

            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"
                        }
            
            #line default
            #line hidden
WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3509), Tuple.Create("\"", 3547)
            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3516), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Uploads")
            
            #line default
            #line hidden
, 3516), false)
);

WriteLiteral(">File Upload</a>\r\n");

            
            #line 83 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuUpload ?? false)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" src=\"/content/images/arrow.png\"");

WriteLiteral(" class=\"arrow\"");

WriteLiteral(" height=\"12\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n");

            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </li>\r\n                        <li ");

            
            #line 88 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuMonitor ?? false)
                            { 

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("class=\"current middle\" \r\n");

            
            #line 91 "..\..\Views\Shared\_Layout.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("class=\"middle\" \r\n");

            
            #line 95 "..\..\Views\Shared\_Layout.cshtml"
                            }
            
            #line default
            #line hidden
WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4177), Tuple.Create("\"", 4215)
            
            #line 95 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4184), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Monitor")
            
            #line default
            #line hidden
, 4184), false)
);

WriteLiteral(">Interface Monitor</a>\r\n");

            
            #line 96 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuMonitor ?? false)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" src=\"/content/images/arrow.png\"");

WriteLiteral(" class=\"arrow\"");

WriteLiteral(" height=\"12\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n");

            
            #line 99 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </li>\r\n                        <li ");

            
            #line 101 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuUser ?? false)
                            { 

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("class=\"current\" \r\n");

            
            #line 104 "..\..\Views\Shared\_Layout.cshtml"
                        }
            
            #line default
            #line hidden
WriteLiteral(" class=\"parent\"><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"cursor: default;\"");

WriteLiteral(" onclick=\"return false;\"");

WriteLiteral(">");

            
            #line 104 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                 Write(ViewBag.Access.Username);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 105 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsMenuUser ?? false)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" src=\"/content/images/arrow.png\"");

WriteLiteral(" class=\"arrow\"");

WriteLiteral(" height=\"12\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n");

            
            #line 108 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 109 "..\..\Views\Shared\_Layout.cshtml"
                             if (ViewBag.IsSecure ?? false)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <ul>\r\n                                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5205), Tuple.Create("\"", 5245)
            
            #line 112 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5212), Tuple.Create<System.Object, System.Int32>(Url.Action("SwitchUser", "User")
            
            #line default
            #line hidden
, 5212), false)
);

WriteLiteral(">Switch User</a></li>\r\n");

            
            #line 113 "..\..\Views\Shared\_Layout.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 113 "..\..\Views\Shared\_Layout.cshtml"
                                     if (ViewBag.Access.IsImpersonating)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5428), Tuple.Create("\"", 5464)
            
            #line 115 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5435), Tuple.Create<System.Object, System.Int32>(Url.Action("Logoff", "User")
            
            #line default
            #line hidden
, 5435), false)
);

WriteLiteral(">Logoff</a></li>\r\n");

            
            #line 116 "..\..\Views\Shared\_Layout.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n");

            
            #line 118 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </li>\r\n                    </ul>\r\n\r\n                    <" +
"div");

WriteLiteral(" class=\"user\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"user-head\"");

WriteLiteral("></div>\r\n                        Connected to ");

            
            #line 124 "..\..\Views\Shared\_Layout.cshtml"
                                 Write((ViewBag.Connection == null) ? "N/A" : ViewBag.Connection.ConnectionName);

            
            #line default
            #line hidden
WriteLiteral(" as ");

            
            #line 124 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                               Write(ViewBag.User.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </header>\r\n    <br />\r\n    <br />\r\n    <div");

WriteLiteral(" id=\"body\"");

WriteLiteral(">\r\n        <section");

WriteLiteral(" class=\"content-wrapper clear-fix\"");

WriteLiteral(">\r\n            <h1>");

            
            #line 134 "..\..\Views\Shared\_Layout.cshtml"
           Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

WriteLiteral("            ");

            
            #line 135 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </section>\r\n    </div>\r\n    <footer>\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n                <br />\r\n                <br />\r\n                &copy; Mars, I" +
"ncorporated and its Affiliates. All Rights Reserved.\r\n            </div>\r\n      " +
"  </div>\r\n    </footer>\r\n    ");

WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
