/******************************************************************************/
/* View Definition                                                            */
/******************************************************************************/
/**
 System  : lads
 Package : ods_cust_hier
 Owner   : lads
 Author  : Steve Gregan

 DESCRIPTION
 -----------
 Local Atlas Data Store - ODS Customer Hierarchy View

 YYYY/MM   Author         Description
 -------   ------         -----------
 2004/11   Steve Gregan   Created

*******************************************************************************/

/*-*/
/* View creation
/*-*/
create or replace force view lads.ods_cust_hier
   (sap_cust_hier_type_code,
    cust_hier_hdr_cntr,
    sap_cust_code_level_1,
    sap_sales_org_code_level_1,
    sap_distbn_chnl_code_level_1,
    sap_division_code_level_1,
    assgmnt_to_hier_level_1,
    node_vldty_start_date_level_1,
    node_vldty_end_date_level_1,
    sap_cust_acc_grp_code_level_1,
    cust_hier_sort_level_1,
    sap_cust_code_level_2,
    sap_sales_org_code_level_2,
    sap_distbn_chnl_code_level_2,
    sap_division_code_level_2,
    assgmnt_to_hier_level_2,
    node_vldty_start_date_level_2,
    node_vldty_end_date_level_2,
    sap_cust_acc_grp_code_level_2,
    cust_hier_sort_level_2,
    sap_cust_code_level_3,
    sap_sales_org_code_level_3,
    sap_distbn_chnl_code_level_3,
    sap_division_code_level_3,
    assgmnt_to_hier_level_3,
    node_vldty_start_date_level_3,
    node_vldty_end_date_level_3,
    sap_cust_acc_grp_code_level_3,
    cust_hier_sort_level_3,
    sap_cust_code_level_4,
    sap_sales_org_code_level_4,
    sap_distbn_chnl_code_level_4,
    sap_division_code_level_4,
    assgmnt_to_hier_level_4,
    node_vldty_start_date_level_4,
    node_vldty_end_date_level_4,
    sap_cust_acc_grp_code_level_4,
    cust_hier_sort_level_4,
    sap_cust_code_level_5,
    sap_sales_org_code_level_5,
    sap_distbn_chnl_code_level_5,
    sap_division_code_level_5,
    assgmnt_to_hier_level_5,
    node_vldty_start_date_level_5,
    node_vldty_end_date_level_5,
    sap_cust_acc_grp_code_level_5,
    cust_hier_sort_level_5,
    sap_cust_code_level_6,
    sap_sales_org_code_level_6,
    sap_distbn_chnl_code_level_6,
    sap_division_code_level_6,
    assgmnt_to_hier_level_6,
    node_vldty_start_date_level_6,
    node_vldty_end_date_level_6,
    sap_cust_acc_grp_code_level_6,
    cust_hier_sort_level_6,
    sap_cust_code_level_7,
    sap_sales_org_code_level_7,
    sap_distbn_chnl_code_level_7,
    sap_division_code_level_7,
    assgmnt_to_hier_level_7,
    node_vldty_start_date_level_7,
    node_vldty_end_date_level_7,
    sap_cust_acc_grp_code_level_7,
    cust_hier_sort_level_7,
    sap_cust_code_level_8,
    sap_sales_org_code_level_8,
    sap_distbn_chnl_code_level_8,
    sap_division_code_level_8,
    assgmnt_to_hier_level_8,
    node_vldty_start_date_level_8,
    node_vldty_end_date_level_8,
    sap_cust_acc_grp_code_level_8,
    cust_hier_sort_level_8,
    sap_cust_code_level_9,
    sap_sales_org_code_level_9,
    sap_distbn_chnl_code_level_9,
    sap_division_code_level_9,
    assgmnt_to_hier_level_9,
    node_vldty_start_date_level_9,
    node_vldty_end_date_level_9,
    sap_cust_acc_grp_code_level_9,
    cust_hier_sort_level_9,
    sap_cust_code_level_10,
    sap_sales_org_code_level_10,
    sap_distbn_chnl_code_level_10,
    sap_division_code_level_10,
    assgmnt_to_hier_level_10,
    node_vldty_start_date_level_10,
    node_vldty_end_date_level_10,
    sap_cust_acc_grp_code_level_10,
    cust_hier_sort_level_10) as 
   select max(t02.hityp) as sap_cust_hier_type_code,
          t01.hdrseq as cust_hier_hdr_cntr,
          max(case when t01.hielv = '01' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_1,
          max(case when t01.hielv = '01' then t01.vkorg end) as sap_sales_org_code_level_1,
          max(case when t01.hielv = '01' then t01.vtweg end) as sap_distbn_chnl_code_level_1,
          max(case when t01.hielv = '01' then t01.spart end) as sap_division_code_level_1,
          max(case when t01.hielv = '01' then t01.hzuor end) as assgmnt_to_hier_level_1,
          max(case when t01.hielv = '01' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_1,
          max(case when t01.hielv = '01' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_1,
          max(case when t01.hielv = '01' then t01.ktokd end) as sap_cust_acc_grp_code_level_1,
          max(case when t01.hielv = '01' then t01.sortl end) as cust_hier_sort_level_1,
          max(case when t01.hielv = '02' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_2,
          max(case when t01.hielv = '02' then t01.vkorg end) as sap_sales_org_code_level_2,
          max(case when t01.hielv = '02' then t01.vtweg end) as sap_distbn_chnl_code_level_2,
          max(case when t01.hielv = '02' then t01.spart end) as sap_division_code_level_2,
          max(case when t01.hielv = '02' then t01.hzuor end) as assgmnt_to_hier_level_2,
          max(case when t01.hielv = '02' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_2,
          max(case when t01.hielv = '02' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_2,
          max(case when t01.hielv = '02' then t01.ktokd end) as sap_cust_acc_grp_code_level_2,
          max(case when t01.hielv = '02' then t01.sortl end) as cust_hier_sort_level_2,
          max(case when t01.hielv = '03' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_3,
          max(case when t01.hielv = '03' then t01.vkorg end) as sap_sales_org_code_level_3,
          max(case when t01.hielv = '03' then t01.vtweg end) as sap_distbn_chnl_code_level_3,
          max(case when t01.hielv = '03' then t01.spart end) as sap_division_code_level_3,
          max(case when t01.hielv = '03' then t01.hzuor end) as assgmnt_to_hier_level_3,
          max(case when t01.hielv = '03' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_3,
          max(case when t01.hielv = '03' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_3,
          max(case when t01.hielv = '03' then t01.ktokd end) as sap_cust_acc_grp_code_level_3,
          max(case when t01.hielv = '03' then t01.sortl end) as cust_hier_sort_level_3,
          max(case when t01.hielv = '04' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_4,
          max(case when t01.hielv = '04' then t01.vkorg end) as sap_sales_org_code_level_4,
          max(case when t01.hielv = '04' then t01.vtweg end) as sap_distbn_chnl_code_level_4,
          max(case when t01.hielv = '04' then t01.spart end) as sap_division_code_level_4,
          max(case when t01.hielv = '04' then t01.hzuor end) as assgmnt_to_hier_level_4,
          max(case when t01.hielv = '04' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_4,
          max(case when t01.hielv = '04' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_4,
          max(case when t01.hielv = '04' then t01.ktokd end) as sap_cust_acc_grp_code_level_4,
          max(case when t01.hielv = '04' then t01.sortl end) as cust_hier_sort_level_4,
          max(case when t01.hielv = '05' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_5,
          max(case when t01.hielv = '05' then t01.vkorg end) as sap_sales_org_code_level_5,
          max(case when t01.hielv = '05' then t01.vtweg end) as sap_distbn_chnl_code_level_5,
          max(case when t01.hielv = '05' then t01.spart end) as sap_division_code_level_5,
          max(case when t01.hielv = '05' then t01.hzuor end) as assgmnt_to_hier_level_5,
          max(case when t01.hielv = '05' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_5,
          max(case when t01.hielv = '05' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_5,
          max(case when t01.hielv = '05' then t01.ktokd end) as sap_cust_acc_grp_code_level_5,
          max(case when t01.hielv = '05' then t01.sortl end) as cust_hier_sort_level_5,
          max(case when t01.hielv = '06' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_6,
          max(case when t01.hielv = '06' then t01.vkorg end) as sap_sales_org_code_level_6,
          max(case when t01.hielv = '06' then t01.vtweg end) as sap_distbn_chnl_code_level_6,
          max(case when t01.hielv = '06' then t01.spart end) as sap_division_code_level_6,
          max(case when t01.hielv = '06' then t01.hzuor end) as assgmnt_to_hier_level_6,
          max(case when t01.hielv = '06' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_6,
          max(case when t01.hielv = '06' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_6,
          max(case when t01.hielv = '06' then t01.ktokd end) as sap_cust_acc_grp_code_level_6,
          max(case when t01.hielv = '06' then t01.sortl end) as cust_hier_sort_level_6,
          max(case when t01.hielv = '07' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_7,
          max(case when t01.hielv = '07' then t01.vkorg end) as sap_sales_org_code_level_7,
          max(case when t01.hielv = '07' then t01.vtweg end) as sap_distbn_chnl_code_level_7,
          max(case when t01.hielv = '07' then t01.spart end) as sap_division_code_level_7,
          max(case when t01.hielv = '07' then t01.hzuor end) as assgmnt_to_hier_level_7,
          max(case when t01.hielv = '07' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_7,
          max(case when t01.hielv = '07' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_7,
          max(case when t01.hielv = '07' then t01.ktokd end) as sap_cust_acc_grp_code_level_7,
          max(case when t01.hielv = '07' then t01.sortl end) as cust_hier_sort_level_7,
          max(case when t01.hielv = '08' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_8,
          max(case when t01.hielv = '08' then t01.vkorg end) as sap_sales_org_code_level_8,
          max(case when t01.hielv = '08' then t01.vtweg end) as sap_distbn_chnl_code_level_8,
          max(case when t01.hielv = '08' then t01.spart end) as sap_division_code_level_8,
          max(case when t01.hielv = '08' then t01.hzuor end) as assgmnt_to_hier_level_8,
          max(case when t01.hielv = '08' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_8,
          max(case when t01.hielv = '08' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_8,
          max(case when t01.hielv = '08' then t01.ktokd end) as sap_cust_acc_grp_code_level_8,
          max(case when t01.hielv = '08' then t01.sortl end) as cust_hier_sort_level_8,
          max(case when t01.hielv = '09' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_9,
          max(case when t01.hielv = '09' then t01.vkorg end) as sap_sales_org_code_level_9,
          max(case when t01.hielv = '09' then t01.vtweg end) as sap_distbn_chnl_code_level_9,
          max(case when t01.hielv = '09' then t01.spart end) as sap_division_code_level_9,
          max(case when t01.hielv = '09' then t01.hzuor end) as assgmnt_to_hier_level_9,
          max(case when t01.hielv = '09' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_9,
          max(case when t01.hielv = '09' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_9,
          max(case when t01.hielv = '09' then t01.ktokd end) as sap_cust_acc_grp_code_level_9,
          max(case when t01.hielv = '09' then t01.sortl end) as cust_hier_sort_level_9,
          max(case when t01.hielv = '10' then lads_trim_code(t01.kunnr) end) as sap_cust_code_level_10,
          max(case when t01.hielv = '10' then t01.vkorg end) as sap_sales_org_code_level_10,
          max(case when t01.hielv = '10' then t01.vtweg end) as sap_distbn_chnl_code_level_10,
          max(case when t01.hielv = '10' then t01.spart end) as sap_division_code_level_10,
          max(case when t01.hielv = '10' then t01.hzuor end) as assgmnt_to_hier_level_10,
          max(case when t01.hielv = '10' then lads_to_date(t01.datab,'yyyymmdd') end) as node_vldty_start_date_level_10,
          max(case when t01.hielv = '10' then lads_to_date(t01.datbi,'yyyymmdd') end) as node_vldty_end_date_level_10,
          max(case when t01.hielv = '10' then t01.ktokd end) as sap_cust_acc_grp_code_level_10,
          max(case when t01.hielv = '10' then t01.sortl end) as cust_hier_sort_level_10
     from lads_hie_cus_det t01,
          lads_hie_cus_hdr t02
    where t01.hdrdat = t02.hdrdat
      and t01.hdrseq = t02.hdrseq
      and t01.hdrdat in (select max(hdrdat) as hdrdat from lads_hie_cus_hdr where lads_status = '1')
    group by t01.hdrdat,
             t01.hdrseq;

/*-*/
/* Authority
/*-*/
grant select on lads.ods_cust_hier to od with grant option;

/*-*/
/* Synonym
/*-*/
create or replace public synonym ods_cust_hier for lads.ods_cust_hier;

