#!/bin/ksh
# ---------------------------------------------------------------------------
# SCRIPT  : ics_archive_file.sh
# AUTHOR  : Ben Halicki
# DATE    : 05-JAN-2011
# PARAMS  : 1 - S_FILE_NAME     # Source file name (full path)
#
# ---------------------------------------------------------------------------
#            F U N C T I O N A L     O V E R V I E W
# ---------------------------------------------------------------------------
# Modification history at end of script
#
# This script has been written specifically for the ANZ Interface Control
# System (ANZICS) used to interface between and local site applications.
# The script handles the loading of files generated by the ICS to a queue
# on Maestro (which then handles its processing to Atlas) using mqft
#
# ---------------------------------------------------------------------------

SCRIPT_PATH=${0%/*}

# Includes the utility files so we can access their variables and functions
. ${SCRIPT_PATH}/ics_utilities.sh

# --------------------------------------------------------------------------
#
# setup_config Description:
# Configure the scripts variables
#
# Parameters:
# 1 - The basename of the program as it was called (i.e. $0 from the calling
#   script.
# --------------------------------------------------------------------------
setup_config()
{
    # initialise the utlities script
    initialise_utilities $1
}

# --------------------------------------------------------------------------
#
# check_params Description:
# Ensure that passed parameters have values.
#
# Parameters: <none>
#
# --------------------------------------------------------------------------
check_params()
{
    if  [[ -z $S_FILE_NAME ]] ; then
        error_exit "ERROR: [check_params] File to cleanup not specified"
    else
        log_file "INFO: [check_params] Verified script input parameters" "HARMLESS"
    fi
}

# --------------------------------------------------------------------------
#
# clean_up_local Description:
# Cleanup any temporary files created by this script.
#
# Parameters: <none>
#
# --------------------------------------------------------------------------
clean_up_local()
{
    clean_up
}

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

S_FILE_NAME=${1}    # Variable: Source file name (full path)

setup_config $0     # Function: Setup script variables

log_file "INFO: [main] Initialized [${SCRIPT_ID}] script for cleanup of ICS inbound loader file [${S_FILE_NAME}]" "HARMLESS"
log_file "INFO: [main] Log file location : [${TMP_OUT}]" "HARMLESS"

check_params                                      # Function: Check passed parameters have values
archive_file "${INBOUND_PATH}/${S_FILE_NAME}"     # move source file to archive directory on local filesystem 
clean_up_local                                    # Function: Remove Temporary Files

log_file "INFO: [main] Completion of script [${SCRIPT_ID}] for cleanup of ICS inbound loader file [${S_FILE_NAME}]" "HARMLESS"

exit 0              # Exit: Exit script with successful flag (0)

# ---------------------------------------------------------------------------
#            M O D I F I C A T I O N   H I S T O R Y
# ---------------------------------------------------------------------------
# Version Date        Author        Modification
# ------- ----------- ------------- --------------------------
# 1.0     05-JAN-2011 B. Halicki    Original
#
# ---------------------------------------------------------------------------
