ALTER TABLE PR.PRICE_ITEM ADD (
  CONSTRAINT PI_PM_FK01 
 FOREIGN KEY (PRICE_MDL_ID) 
 REFERENCES PR.PRICE_MDL (PRICE_MDL_ID));

ALTER TABLE PR.PRICE_MDL_BY_SALES_AREA ADD (
  CONSTRAINT PMBSA_PDC_FK03 
 FOREIGN KEY (PRICE_DISTBN_CHNL_ID) 
 REFERENCES PR.PRICE_DISTBN_CHNL (PRICE_DISTBN_CHNL_ID),
  CONSTRAINT PMBSA_PM_FK01 
 FOREIGN KEY (PRICE_MDL_ID) 
 REFERENCES PR.PRICE_MDL (PRICE_MDL_ID),
  CONSTRAINT PMBSA_PSO_FK02 
 FOREIGN KEY (PRICE_SALES_ORG_ID) 
 REFERENCES PR.PRICE_SALES_ORG (PRICE_SALES_ORG_ID));

ALTER TABLE PR.REPORT ADD (
  CONSTRAINT R_PDC_FK03 
 FOREIGN KEY (PRICE_DISTBN_CHNL_ID) 
 REFERENCES PR.PRICE_DISTBN_CHNL (PRICE_DISTBN_CHNL_ID),
  CONSTRAINT R_PM_FK01 
 FOREIGN KEY (PRICE_MDL_ID) 
 REFERENCES PR.PRICE_MDL (PRICE_MDL_ID),
  CONSTRAINT R_PSO_FK02 
 FOREIGN KEY (PRICE_SALES_ORG_ID) 
 REFERENCES PR.PRICE_SALES_ORG (PRICE_SALES_ORG_ID),
  CONSTRAINT R_RG_FK04 
 FOREIGN KEY (REPORT_GRP_ID) 
 REFERENCES PR.REPORT_GRP (REPORT_GRP_ID));

ALTER TABLE PR.REPORT_ITEM ADD (
  CONSTRAINT RI_PI_FK02 
 FOREIGN KEY (PRICE_ITEM_ID) 
 REFERENCES PR.PRICE_ITEM (PRICE_ITEM_ID),
  CONSTRAINT RI_R_FK01 
 FOREIGN KEY (REPORT_ID) 
 REFERENCES PR.REPORT (REPORT_ID));

ALTER TABLE PR.REPORT_MATL ADD (
  CONSTRAINT RM_R_FK01 
 FOREIGN KEY (REPORT_ID) 
 REFERENCES PR.REPORT (REPORT_ID));

ALTER TABLE PR.REPORT_RULE ADD (
  CONSTRAINT RR_R_FK01 
 FOREIGN KEY (REPORT_ID) 
 REFERENCES PR.REPORT (REPORT_ID));

ALTER TABLE PR.REPORT_RULE_DETL ADD (
  CONSTRAINT RRD_PRD_FK02 
 FOREIGN KEY (PRICE_RULE_TYPE_ID) 
 REFERENCES PR.PRICE_RULE_TYPE (PRICE_RULE_TYPE_ID),
  CONSTRAINT RRD_RR_FK01 
 FOREIGN KEY (REPORT_RULE_ID) 
 REFERENCES PR.REPORT_RULE (REPORT_RULE_ID));


