
CREATE TABLE PR.PRICE_SALES_ORG
(
  PRICE_SALES_ORG_ID    NUMBER(20)              NOT NULL,
  PRICE_SALES_ORG_CODE  VARCHAR2(20 BYTE)       NOT NULL,
  PRICE_SALES_ORG_NAME  VARCHAR2(200 BYTE)
);

COMMENT ON TABLE PR.PRICE_SALES_ORG IS 'This table holds the possible sales organisations that are available within this price list generator.';

COMMENT ON COLUMN PR.PRICE_SALES_ORG.PRICE_SALES_ORG_ID IS 'Price list sales org id.';

COMMENT ON COLUMN PR.PRICE_SALES_ORG.PRICE_SALES_ORG_CODE IS 'Price list sales org code.';

COMMENT ON COLUMN PR.PRICE_SALES_ORG.PRICE_SALES_ORG_NAME IS 'Price list sales org name.';

CREATE UNIQUE INDEX PR.PRICE_SALES_ORG_UK02 ON PR.PRICE_SALES_ORG
(PRICE_SALES_ORG_CODE);

CREATE OR REPLACE PUBLIC SYNONYM PRICE_SALES_ORG FOR PR.PRICE_SALES_ORG;

ALTER TABLE PR.PRICE_SALES_ORG ADD (
  CONSTRAINT PRICE_SALES_ORG_PK01
 PRIMARY KEY
 (PRICE_SALES_ORG_ID));

GRANT SELECT ON PR.PRICE_SALES_ORG TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PRICE_SALES_ORG TO PR_APP;

