
CREATE TABLE PR.PRICE_DISTBN_CHNL
(
  PRICE_DISTBN_CHNL_ID    NUMBER(20)            NOT NULL,
  PRICE_DISTBN_CHNL_CODE  VARCHAR2(20 BYTE)     NOT NULL,
  PRICE_DISTBN_CHNL_NAME  VARCHAR2(200 BYTE)
);

COMMENT ON TABLE PR.PRICE_DISTBN_CHNL IS 'This table holds the possible price list generator distribution channels.';

COMMENT ON COLUMN PR.PRICE_DISTBN_CHNL.PRICE_DISTBN_CHNL_ID IS 'Price list distribution channel id.';

COMMENT ON COLUMN PR.PRICE_DISTBN_CHNL.PRICE_DISTBN_CHNL_CODE IS 'Price list distribution channel code.';

COMMENT ON COLUMN PR.PRICE_DISTBN_CHNL.PRICE_DISTBN_CHNL_NAME IS 'Price list distribution channel name.';

CREATE UNIQUE INDEX PR.PRICE_DISTBN_CHNL_UK02 ON PR.PRICE_DISTBN_CHNL
(PRICE_DISTBN_CHNL_CODE);

CREATE OR REPLACE PUBLIC SYNONYM PRICE_DISTBN_CHNL FOR PR.PRICE_DISTBN_CHNL;

ALTER TABLE PR.PRICE_DISTBN_CHNL ADD (
  CONSTRAINT PRICE_DISTBN_CHNL_PK01
 PRIMARY KEY
 (PRICE_DISTBN_CHNL_ID));

GRANT SELECT ON PR.PRICE_DISTBN_CHNL TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PRICE_DISTBN_CHNL TO PR_APP;

