
CREATE TABLE PR.PRICE_MDL_BY_SALES_AREA
(
  PRICE_MDL_ID          NUMBER(20)              NOT NULL,
  PRICE_SALES_ORG_ID    NUMBER(20)              NOT NULL,
  PRICE_DISTBN_CHNL_ID  NUMBER(20)              NOT NULL
);

COMMENT ON TABLE PR.PRICE_MDL_BY_SALES_AREA IS 'This table holds the possible price model sales area combinations.';

COMMENT ON COLUMN PR.PRICE_MDL_BY_SALES_AREA.PRICE_MDL_ID IS 'Price list model id.';

COMMENT ON COLUMN PR.PRICE_MDL_BY_SALES_AREA.PRICE_SALES_ORG_ID IS 'Price list sales organisation.';

COMMENT ON COLUMN PR.PRICE_MDL_BY_SALES_AREA.PRICE_DISTBN_CHNL_ID IS 'Price list distribution channel.';

CREATE OR REPLACE PUBLIC SYNONYM PRICE_MDL_BY_SALES_AREA FOR PR.PRICE_MDL_BY_SALES_AREA;

ALTER TABLE PR.PRICE_MDL_BY_SALES_AREA ADD (
  CONSTRAINT PRICE_MDL_BY_SALES_AREA_PK01
 PRIMARY KEY
 (PRICE_MDL_ID, PRICE_SALES_ORG_ID, PRICE_DISTBN_CHNL_ID));

ALTER TABLE PR.PRICE_MDL_BY_SALES_AREA ADD (
  CONSTRAINT PMBSA_PDC_FK03 
 FOREIGN KEY (PRICE_DISTBN_CHNL_ID) 
 REFERENCES PR.PRICE_DISTBN_CHNL (PRICE_DISTBN_CHNL_ID),
  CONSTRAINT PMBSA_PM_FK01 
 FOREIGN KEY (PRICE_MDL_ID) 
 REFERENCES PR.PRICE_MDL (PRICE_MDL_ID),
  CONSTRAINT PMBSA_PSO_FK02 
 FOREIGN KEY (PRICE_SALES_ORG_ID) 
 REFERENCES PR.PRICE_SALES_ORG (PRICE_SALES_ORG_ID));

GRANT SELECT ON PR.PRICE_MDL_BY_SALES_AREA TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PRICE_MDL_BY_SALES_AREA TO PR_APP;

