
CREATE TABLE PR.REPORT_MATL_EXCLUDE
(
  REPORT_ID  NUMBER(20)                         NOT NULL,
  MATL_CODE  VARCHAR2(20 BYTE)                  NOT NULL
);

COMMENT ON TABLE PR.REPORT_MATL_EXCLUDE IS 'This is the list of materials that are to be excluded from the report - automatic update only.  These are the report TDU''s.';

COMMENT ON COLUMN PR.REPORT_MATL_EXCLUDE.REPORT_ID IS 'The report id.';

COMMENT ON COLUMN PR.REPORT_MATL_EXCLUDE.MATL_CODE IS 'The material code in question.';

CREATE OR REPLACE PUBLIC SYNONYM REPORT_MATL_EXCLUDE FOR PR.REPORT_MATL_EXCLUDE;

ALTER TABLE PR.REPORT_MATL_EXCLUDE ADD (
  CONSTRAINT REPORT_MATL_EXCLUDE_PK01
 PRIMARY KEY
 (REPORT_ID, MATL_CODE));

GRANT SELECT ON PR.REPORT_MATL_EXCLUDE TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.REPORT_MATL_EXCLUDE TO PR_APP;

