
CREATE TABLE PR.REPORT_RULE_DETL
(
  REPORT_RULE_ID      NUMBER(20)                NOT NULL,
  PRICE_RULE_TYPE_ID  NUMBER(20)                NOT NULL,
  RULE_VLU            VARCHAR2(200 BYTE)        NOT NULL,
  RULE_NOT            VARCHAR2(1 BYTE)          NOT NULL
);

COMMENT ON TABLE PR.REPORT_RULE_DETL IS 'This table contains the actual rule values that are anded together within the selection.';

COMMENT ON COLUMN PR.REPORT_RULE_DETL.REPORT_RULE_ID IS 'The report rule id.';

COMMENT ON COLUMN PR.REPORT_RULE_DETL.PRICE_RULE_TYPE_ID IS 'This is a link to the rule type id.';

COMMENT ON COLUMN PR.REPORT_RULE_DETL.RULE_VLU IS 'The value that is being applied to this rule.';

COMMENT ON COLUMN PR.REPORT_RULE_DETL.RULE_NOT IS 'This is N if the rule shouldn''t have the not in operator applied to it.';

CREATE OR REPLACE PUBLIC SYNONYM REPORT_RULE_DETL FOR PR.REPORT_RULE_DETL;

ALTER TABLE PR.REPORT_RULE_DETL ADD (
  CONSTRAINT REPORT_RULE_DETL_PK01
 PRIMARY KEY
 (REPORT_RULE_ID, PRICE_RULE_TYPE_ID));

GRANT SELECT ON PR.REPORT_RULE_DETL TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.REPORT_RULE_DETL TO PR_APP;

