
CREATE TABLE PR.REPORT_TERM
(
  REPORT_ID   NUMBER(20)                        NOT NULL,
  SORT_ORDER  NUMBER(8)                         NOT NULL,
  VALUE       VARCHAR2(1000 BYTE),
  DATA_FRMT   VARCHAR2(4000 BYTE)
);

CREATE OR REPLACE PUBLIC SYNONYM REPORT_TERM FOR PR.REPORT_TERM;

ALTER TABLE PR.REPORT_TERM ADD (
  CONSTRAINT REPORT_TERM_PK
 PRIMARY KEY
 (REPORT_ID, SORT_ORDER));

GRANT SELECT ON PR.REPORT_TERM TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.REPORT_TERM TO PR_APP;

