
CREATE TABLE PR.REPORT_MATL
(
  REPORT_ID  NUMBER(20)                         NOT NULL,
  MATL_CODE  VARCHAR2(20 BYTE)                  NOT NULL
);

COMMENT ON TABLE PR.REPORT_MATL IS 'This is the list of materials that are to be included on the report.  These are the report TDU''s.';

COMMENT ON COLUMN PR.REPORT_MATL.REPORT_ID IS 'The report id.';

COMMENT ON COLUMN PR.REPORT_MATL.MATL_CODE IS 'The material code in question.';

CREATE OR REPLACE PUBLIC SYNONYM REPORT_MATL FOR PR.REPORT_MATL;

ALTER TABLE PR.REPORT_MATL ADD (
  CONSTRAINT REPORT_MATL_PK01
 PRIMARY KEY
 (REPORT_ID, MATL_CODE));

ALTER TABLE PR.REPORT_MATL ADD (
  CONSTRAINT RM_R_FK01 
 FOREIGN KEY (REPORT_ID) 
 REFERENCES PR.REPORT (REPORT_ID));

GRANT SELECT ON PR.REPORT_MATL TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.REPORT_MATL TO PR_APP;

