
CREATE TABLE PR.REPORT_GRP_TERM
(
  REPORT_GRP_ID   NUMBER(20)                        NOT NULL,
  SORT_ORDER      NUMBER(8)                         NOT NULL,
  VALUE           VARCHAR2(1000 BYTE),
  DATA_FRMT       VARCHAR2(4000 BYTE)
);

CREATE OR REPLACE PUBLIC SYNONYM REPORT_GRP_TERM FOR PR.REPORT_GRP_TERM;

ALTER TABLE PR.REPORT_GRP_TERM ADD (
  CONSTRAINT REPORT_GRP_TERM_PK
 PRIMARY KEY
 (REPORT_GRP_ID, SORT_ORDER));

GRANT SELECT ON PR.REPORT_GRP_TERM TO LICS_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.REPORT_GRP_TERM TO PR_APP;

