DROP PROCEDURE MANU_APP.DT_DROPUSEROBJECTBYID;

CREATE OR REPLACE PROCEDURE MANU_APP.DT_DROPUSEROBJECTBYID ( PARAM_ID IN NUMBER ) AS BEGIN DELETE FROM MICROSOFTDTPROPERTIES WHERE OBJECTID = PARAM_ID; END DT_DROPUSEROBJECTBYID;
/


