DROP MATERIALIZED VIEW CONDITION_TYPE;

CREATE MATERIALIZED VIEW CONDITION_TYPE 
TABLESPACE OD_DATA
NOCACHE
LOGGING
NOPARALLEL
USING INDEX
            TABLESPACE OD_DATA
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT "CONDITION_TYPE"."SAP_CNDTN_TYPE_CODE" "SAP_CNDTN_TYPE_CODE","CONDITION_TYPE"."CNDTN_TYPE_DESC" "CNDTN_TYPE_DESC","CONDITION_TYPE"."CNDTN_TYPE_LUPDP" "CNDTN_TYPE_LUPDP","CONDITION_TYPE"."CNDTN_TYPE_LUPDT" "CNDTN_TYPE_LUPDT" FROM "CONDITION_TYPE"@AP0093P.WORLD "CONDITION_TYPE";

CREATE UNIQUE INDEX CONDITION_TYPE_PK ON CONDITION_TYPE
(SAP_CNDTN_TYPE_CODE)
LOGGING
TABLESPACE OD_DATA
NOPARALLEL;

GRANT SELECT ON  CONDITION_TYPE TO DW_APP WITH GRANT OPTION;


CREATE OR REPLACE PUBLIC SYNONYM CONDITION_TYPE FOR CONDITION_TYPE;


