DROP MATERIALIZED VIEW MATERIAL_LIST_PRICE;

CREATE MATERIALIZED VIEW MATERIAL_LIST_PRICE 
TABLESPACE OD_DATA
NOCACHE
LOGGING
NOPARALLEL
REFRESH COMPLETE ON DEMAND
WITH ROWID
AS 
SELECT "MATERIAL_LIST_PRICE"."SAP_MATERIAL_CODE" "SAP_MATERIAL_CODE",
       "MATERIAL_LIST_PRICE"."SAP_CNDTN_TYPE_CODE" "SAP_CNDTN_TYPE_CODE",
       "MATERIAL_LIST_PRICE"."SAP_SALES_ORG_CODE" "SAP_SALES_ORG_CODE",
       "MATERIAL_LIST_PRICE"."SAP_DISTBN_CHNL_CODE" "SAP_DISTBN_CHNL_CODE",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE_VALID_FROM" "MATERIAL_LIST_PRICE_VALID_FROM",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE_VALID_TO" "MATERIAL_LIST_PRICE_VALID_TO",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE" "MATERIAL_LIST_PRICE",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE_CRRCY_CODE" "MATERIAL_LIST_PRICE_CRRCY_CODE",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE_PER_UNITS" "MATERIAL_LIST_PRICE_PER_UNITS",
       "MATERIAL_LIST_PRICE"."MATERIAL_LIST_PRICE_UOM_CODE" "MATERIAL_LIST_PRICE_UOM_CODE"
  FROM "MATERIAL_LIST_PRICE"@AP0093P.WORLD "MATERIAL_LIST_PRICE";

GRANT SELECT ON  MATERIAL_LIST_PRICE TO DW_APP WITH GRANT OPTION;

CREATE OR REPLACE PUBLIC SYNONYM MATERIAL_LIST_PRICE FOR MATERIAL_LIST_PRICE;


