-- This script creates the table used by PMXPXI03_LOADER.  

  CREATE TABLE "PMX_359_PROMOTIONS" 
   (	"XACTN_SEQ" NUMBER(15,0), 
	"BATCH_SEQ" NUMBER(15,0), 
	"BATCH_REC_SEQ" NUMBER(10,0), 
	"IC_RECORD_TYPE" VARCHAR2(6 CHAR), 
	"PX_COMPANY_CODE" VARCHAR2(3 CHAR), 
	"PX_DIVISION_CODE" VARCHAR2(3 CHAR), 
	"CUSTOMER_HIERARCHY" VARCHAR2(10 CHAR), 
	"SALES_DEAL" VARCHAR2(10 CHAR), 
	"MATERIAL" VARCHAR2(18 CHAR), 
	"BUY_START_DATE" DATE, 
	"BUY_STOP_DATE" DATE, 
	"TRANSACTION_CODE" VARCHAR2(4 CHAR), 
	"DESCRIPTION" VARCHAR2(40 CHAR), 
	"SALES_ORG" VARCHAR2(4 CHAR), 
	"RATE" NUMBER(12,2), 
	"USER_1" VARCHAR2(10 CHAR), 
	"USER_2" VARCHAR2(10 CHAR), 
	"ACTION_CODE" VARCHAR2(1 CHAR), 
	"BONUS_STOCK_DESCRIPTION" VARCHAR2(100 CHAR), 
	"BONUS_STOCK_HURDLE" NUMBER(9,2), 
	"BONUS_STOCK_RECEIVE" NUMBER(9,2), 
	"BONUS_STOCK_SKU_CODE" VARCHAR2(18 CHAR), 
	"RATE_UNIT" VARCHAR2(5 CHAR), 
	"CONDITION_PRICING_UNIT" VARCHAR2(5 CHAR), 
	"CONDITION_UOM" VARCHAR2(3 CHAR), 
	"SAP_PROMO_NUMBER" VARCHAR2(10 CHAR), 
	"CURRENCY" VARCHAR2(3 CHAR), 
	"UOM_STR_UNIT" VARCHAR2(3 CHAR), 
	"UOM_STR_SALEABLE" VARCHAR2(3 CHAR), 
	"PROMO_PRICE_SALEABLE" VARCHAR2(10 CHAR), 
	"PROMO_PRICE_UNIT" VARCHAR2(10 CHAR), 
	"TRANSACTION_AMOUNT" VARCHAR2(10 CHAR), 
	"PAYER_CODE" VARCHAR2(20 CHAR), 
	"CONDITION_FLAG" VARCHAR2(1 CHAR), 
	"BUSINESS_SEGMENT" VARCHAR2(2 CHAR), 
	"RATE_MULTIPLIER" NUMBER(4,0), 
	"CONDITION_TYPE_CODE" VARCHAR2(1 CHAR), 
	"PRICING_CONDITION_CODE" VARCHAR2(4 CHAR), 
	"CONDITION_TABLE_REF" VARCHAR2(5 CHAR), 
	"CUST_DIV_CODE" VARCHAR2(2 CHAR), 
	"ORDER_TYPE_CODE" VARCHAR2(4 CHAR), 
	"VAKEY" VARCHAR2(50 CHAR), 
	"PX_XACTN_ID" NUMBER(10,0), 
	"NEW_CUSTOMER_HIERARCHY" VARCHAR2(10 CHAR), 
	"NEW_MATERIAL" VARCHAR2(18 CHAR), 
	"NEW_RATE" NUMBER(12,2), 
	"NEW_RATE_UNIT" VARCHAR2(5 CHAR), 
	"NEW_RATE_MULTIPLIER" varchar2(5 char), 
	 CONSTRAINT "PMX_359_PROMOTIONS_PK" PRIMARY KEY ("XACTN_SEQ"));

  CREATE UNIQUE INDEX "PMX_359_PROMOTIONS_BATCH_SEQ" ON "PMX_359_PROMOTIONS" ("BATCH_SEQ", "BATCH_REC_SEQ");

  CREATE INDEX "PMX_359_PROMOTIONS_PX_XACTN_ID" ON "PMX_359_PROMOTIONS" ("PX_XACTN_ID");

  CREATE UNIQUE INDEX "PMX_359_PROMOTIONS_UK" ON "PMX_359_PROMOTIONS" ("VAKEY", "PRICING_CONDITION_CODE", "XACTN_SEQ", "SALES_DEAL");
  
  create or replace public synonym pmx_359_promotions for pxi.pmx_359_promotions;
  
  grant select, insert, update, delete on pmx_359_promotions to pxi_app;
