/******************************************************************/
/* System  : QVI                                                  */
/* Object  : _qvi_qv_load                                         */
/* Author  : Steve Gregan                                         */
/* Date    : March 2012                                           */
/*                                                                */
/******************************************************************/

/*----------------------------------------*/
/* MUST BE CONNECTED AS USER QV or QV_APP */
/*----------------------------------------*/

/*-*/
/* Create the QVI control data
/*-*/
prompt CREATING DASHBOARD DEFINITIONS ...

-- -----------------------------------------------------------------------------
-- FPPS Dashboard
insert into qv.qvi_das_defn (qdd_das_code,qdd_das_name,qdd_das_status,qdd_upd_user,qdd_upd_date) values('FPPS','FPPS Dashboard','1',user,sysdate);

-- -----------------------------------------------------------------------------
-- FPPS Facts 
insert into qv.qvi_fac_defn (qfd_das_code,qfd_fac_code,qfd_fac_name,qfd_fac_status,qfd_fac_build,qfd_fac_table,qfd_fac_type,qfd_job_group,qfd_ema_group,qfd_pol_flag,qfd_flg_iface,qfd_flg_mname,qfd_upd_user,qfd_upd_date) values('FPPS','ACTUAL_3298','FPPS - 3298 Asia Pacific Cons','1','qv_app.qvi_fppqvi06_fact_pkg.build_fact','qv_app.qvi_fppqvi06_fact_pkg.get_table','qv_app.qvi_fppqvi06_tab','QVI','group_anz_bi_deplyment_team_-_test@effem.com','1',null,null,user,sysdate);
insert into qv.qvi_fac_defn (qfd_das_code,qfd_fac_code,qfd_fac_name,qfd_fac_status,qfd_fac_build,qfd_fac_table,qfd_fac_type,qfd_job_group,qfd_ema_group,qfd_pol_flag,qfd_flg_iface,qfd_flg_mname,qfd_upd_user,qfd_upd_date) values('FPPS','PLAN_3298','FPPS - 3298 Asia Pacific Cons','1','qv_app.qvi_fppqvi06_fact_pkg.build_fact','qv_app.qvi_fppqvi06_fact_pkg.get_table','qv_app.qvi_fppqvi06_tab','QVI','group_anz_bi_deplyment_team_-_test@effem.com','1',null,null,user,sysdate);

-- -----------------------------------------------------------------------------
-- FPPS Fact Parts
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1001_HKD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 1001 Hong Kong Mkt - HKD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1001_HKD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 1001 Hong Kong Mkt - HKD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1226_THB_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 1226 Thailand Mkt - THB - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1226_THB_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 1226 Thailand Mkt - THB - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1227_THB_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 1227 Pakchong Fct - THB - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1227_THB_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 1227 Pakchong Fct - THB - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1961_IDR_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 1961 Indonesia - Medan & Jakarta Mkt - IDR - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_1961_IDR_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 1961 Indonesia - Medan & Jakarta Mkt - IDR - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2066_JPY_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 2066 Japan Mkt - JPY - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2066_JPY_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 2066 Japan Mkt - JPY - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2068_TWD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 2068 Taiwan Mkt - TWD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2068_TWD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 2068 Taiwan Mkt - TWD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2069_KRW_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 2069 Korea Mkt - KRW - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2069_KRW_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 2069 Korea Mkt - KRW - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2070_PHP_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 2070 Philippines Mkt - PHP - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2070_PHP_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 2070 Philippines Mkt - PHP - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2436_USD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 2436 EF Asia Mkt - USD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_2436_USD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 2436 EF Asia Mkt - USD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_3190_AUD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 3190 Chocolate Australia Unit - AUD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_3190_AUD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 3190 Chocolate Australia Unit - AUD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_3298_USD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 3298 Asia Pacific Cons - USD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_3298_USD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 3298 Asia Pacific Cons - USD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_5877_USD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 5877 Symbioscience Makassar Unit - USD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_5877_USD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 5877 Symbioscience Makassar Unit - USD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6436_NZD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 6436 New Zealand Mkt - NZD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6436_NZD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 6436 New Zealand Mkt - NZD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6465_NZD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 6465 Wanganui Fct - NZD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6465_NZD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 6465 Wanganui Fct - NZD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6641_AUD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 6641 Birdcare Australia Unit - AUD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_6641_AUD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 6641 Birdcare Australia Unit - AUD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_7032_CNY_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 7032 Jiaxing Fct - CNY - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_7032_CNY_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 7032 Jiaxing Fct - CNY - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8186_MYR_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 8186 Malaysia Mkt - MYR - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8186_MYR_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 8186 Malaysia Mkt - MYR - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8722_CNY_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 8722 Chocolate China Unit - CNY - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8722_CNY_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 8722 Chocolate China Unit - CNY - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8723_CNY_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 8723 Petcare China Unit - CNY - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_8723_CNY_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 8723 Petcare China Unit - CNY - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_9322_USD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 9322 Philippines Duty Free Mkt - USD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_9322_USD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 9322 Philippines Duty Free Mkt - USD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_994_AUD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 994 Petcare Australia Unit - AUD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_994_AUD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 994 Petcare Australia Unit - AUD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_995_AUD_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - 995 Food Australia Unit - AUD - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_995_AUD_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - 995 Food Australia Unit - AUD - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B334_JPY_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - b334 Nutro Company Japan Mkt - JPY - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B334_JPY_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - b334 Nutro Company Japan Mkt - JPY - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B540_IDR_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - b540 Chocolate Indonesia Mkt - IDR - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B540_IDR_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - b540 Chocolate Indonesia Mkt - IDR - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B541_IDR_5_PDITMTOTMKTTOT','3298 Asia Pacific Cons - b541 Petcare Indonesia Mkt - IDR - 5 - PDITMTOTMKTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','ACTUAL_3298','3298_B541_IDR_5_PDTOTTOTTOTTOT','3298 Asia Pacific Cons - b541 Petcare Indonesia Mkt - IDR - 5 - PDTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1001_HKD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 1001 Hong Kong Mkt - HKD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1001_HKD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 1001 Hong Kong Mkt - HKD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1226_THB_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 1226 Thailand Mkt - THB - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1226_THB_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 1226 Thailand Mkt - THB - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1227_THB_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 1227 Pakchong Fct - THB - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1227_THB_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 1227 Pakchong Fct - THB - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1961_IDR_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 1961 Indonesia - Medan & Jakarta Mkt - IDR - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_1961_IDR_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 1961 Indonesia - Medan & Jakarta Mkt - IDR - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2066_JPY_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 2066 Japan Mkt - JPY - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2066_JPY_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 2066 Japan Mkt - JPY - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2068_TWD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 2068 Taiwan Mkt - TWD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2068_TWD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 2068 Taiwan Mkt - TWD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2069_KRW_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 2069 Korea Mkt - KRW - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2069_KRW_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 2069 Korea Mkt - KRW - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2070_PHP_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 2070 Philippines Mkt - PHP - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2070_PHP_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 2070 Philippines Mkt - PHP - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2436_USD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 2436 EF Asia Mkt - USD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_2436_USD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 2436 EF Asia Mkt - USD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_3190_AUD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 3190 Chocolate Australia Unit - AUD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_3190_AUD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 3190 Chocolate Australia Unit - AUD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_3298_USD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 3298 Asia Pacific Cons - USD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_3298_USD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 3298 Asia Pacific Cons - USD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_5877_USD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 5877 Symbioscience Makassar Unit - USD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_5877_USD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 5877 Symbioscience Makassar Unit - USD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6436_NZD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 6436 New Zealand Mkt - NZD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6436_NZD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 6436 New Zealand Mkt - NZD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6465_NZD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 6465 Wanganui Fct - NZD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6465_NZD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 6465 Wanganui Fct - NZD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6641_AUD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 6641 Birdcare Australia Unit - AUD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_6641_AUD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 6641 Birdcare Australia Unit - AUD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_7032_CNY_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 7032 Jiaxing Fct - CNY - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_7032_CNY_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 7032 Jiaxing Fct - CNY - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8186_MYR_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 8186 Malaysia Mkt - MYR - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8186_MYR_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 8186 Malaysia Mkt - MYR - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8722_CNY_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 8722 Chocolate China Unit - CNY - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8722_CNY_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 8722 Chocolate China Unit - CNY - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8723_CNY_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 8723 Petcare China Unit - CNY - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_8723_CNY_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 8723 Petcare China Unit - CNY - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_9322_USD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 9322 Philippines Duty Free Mkt - USD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_9322_USD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 9322 Philippines Duty Free Mkt - USD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_994_AUD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 994 Petcare Australia Unit - AUD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_994_AUD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 994 Petcare Australia Unit - AUD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_995_AUD_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - 995 Food Australia Unit - AUD - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_995_AUD_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - 995 Food Australia Unit - AUD - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B334_JPY_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - b334 Nutro Company Japan Mkt - JPY - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B334_JPY_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - b334 Nutro Company Japan Mkt - JPY - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B540_IDR_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - b540 Chocolate Indonesia Mkt - IDR - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B540_IDR_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - b540 Chocolate Indonesia Mkt - IDR - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B541_IDR_4_OPITMTOTTOTTOT','3298 Asia Pacific Cons - b541 Petcare Indonesia Mkt - IDR - 4 - OPITMTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);
insert into qv.qvi_fac_part (qfp_das_code,qfp_fac_code,qfp_par_code,qfp_par_name,qfp_par_status,qfp_src_table,qfp_src_type,qfp_upd_user,qfp_upd_date) values ('FPPS','PLAN_3298','3298_B541_IDR_4_OPTOTTOTTOTTOT','3298 Asia Pacific Cons - b541 Petcare Indonesia Mkt - IDR - 4 - OPTOTTOTTOTTOT',1,'qv_app.qvi_fppqvi06_fact','qv_app.qvi_fppqvi06_tab',user,sysdate);

prompt CREATING DIMENSION DEFINITIONS ...

/*
insert into qv.qvi_dim_defn values('Dimension Code', 'Dimension Name', '1', 'Dimension_Table_Function', 'Dimension_Data_Type', '0', sysdate, sysdate, user, sysdate);
*/

prompt COMMIT THE LOADING ...

commit;