  drop table pix.pmx_price_conditions;
  
  CREATE TABLE PXI.PMX_PRICE_CONDITIONS (
    CONDITION_TABLE VARCHAR2(5 CHAR), 
    VAKEY VARCHAR2(50 CHAR), 
    COMPANY VARCHAR2(3 CHAR), 
    CUST_DIV_CODE VARCHAR2(2 CHAR), 
    CUST_HIERARCHY_CODE VARCHAR2(10 CHAR), 
    MATL_CODE VARCHAR2(18 CHAR), 
    BUY_START_DATE DATE, 
    BUY_STOP_DATE DATE, 
    PRICING_CONDITION_CODE VARCHAR2(4 CHAR), 
    CONDITION_TYPE_CODE VARCHAR2(1 CHAR), 
    RATE NUMBER(12,2), 
    RATE_UNIT VARCHAR2(5 CHAR), 
    SALES_DEAL VARCHAR2(10 CHAR), 
    RATE_MULTIPLIER VARCHAR2(5 CHAR), 
    ORDER_TYPE_CODE VARCHAR2(4 CHAR)
   );
   
-- Indexes
create index pxi.PMX_PRICE_CONDITIONS_nu01 on pxi.PMX_PRICE_CONDITIONS (vakey, pricing_condition_code);

-- Grants
grant select, insert, update, delete on pxi.PMX_PRICE_CONDITIONS to pxi_app;